/*
 * DX12 replacement for shader 0x1D1EEAC6 (ps_5_1) -- RDR2 tone-mapping pass.
 *
 * Generated by tools/mech-port.mjs from a 3DMigoto decompilation of the game's
 * own DX12 bytecode (captures/msasm/0x1D1EEAC6.ps_5_1.asm), then repaired
 * where the decompiler could not represent an instruction. The arithmetic,
 * register bindings and structured-buffer strides are therefore the game's, not
 * a re-derivation, which is why this file is generated rather than written by
 * hand: retyping the decompilation would only add opportunities for error.
 *
 * Not translated from the Vulkan mod's tonemap_*.frag.vk.glsl. The two renderers
 * differ in this pass; the Vulkan source is used only to decide what RenoDX
 * changes, which is the grading call spliced in at the end.
 *
 * The only behavioural changes are:
 *   - the RenoDX injection constant buffer is added (b13, space50), and
 *   - ApplyGradingAndDisplayMap() runs on the final colour.
 * Everything else, including both tone-map branches and the select between
 * them, is the original arithmetic, so ToneMapper = Vanilla is preserved.
 *
 * Bindings are verified to match the original by tools/verify-bindings.mjs.
 *
 * Unverified in game: this has only been validated by compilation and by
 * comparing the binding slots it reads against the original.
 */
#include "../shared.h"
#include "../tonemap/tonemap.hlsli"

// ---- Created with 3Dmigoto v1.4.9 on Fri Sep 18 01:27:32 2026
struct t118_t {
  float val[59];
};
StructuredBuffer<t118_t> t118 : register(t118);

Buffer<float4> t116 : register(t116);

Texture2D<float4> t114 : register(t114);

Texture2D<float4> t113 : register(t113);

Texture2D<float4> t111 : register(t111);

Texture2D<float4> t110 : register(t110);

Texture2D<float4> t109 : register(t109);

Texture2D<float4> t107 : register(t107);

Texture2D<float4> t106 : register(t106);

Texture2D<float4> t101 : register(t101);

Texture2D<float4> t100 : register(t100);

Texture2D<float4> t95 : register(t95);

Texture2D<float4> t94 : register(t94);

Texture1D<float4> t89 : register(t89);

Texture2D<float4> t90 : register(t90);

Texture2D<float4> t81 : register(t81);

Texture2D<float4> t78 : register(t78);

Texture2D<float4> t77 : register(t77);

Texture2D<float4> t44 : register(t44);

Texture2DArray<float4> t25 : register(t25);

struct t3_t {
  float val[476];
};
StructuredBuffer<t3_t> t3 : register(t3);

struct t2_t {
  float val[501];
};
StructuredBuffer<t2_t> t2 : register(t2);

SamplerState s8_s : register(s8);

SamplerState s2_s : register(s2);

SamplerState s1_s : register(s1);

SamplerState s0_s : register(s0);

cbuffer cb20 : register(b20)
{
  float4 cb20[5];
}

cbuffer cb16 : register(b16)
{
  float4 cb16[88];
}




// 3Dmigoto declarations
#define cmp -


float4 main(
  float4 v0 : SV_Position,
  float4 v1 : TEXCOORD0,
  float v2 : TEXCOORD1) : SV_Target0
{
  float4 o0;
  float4 r0,r1,r2,r3,r4,r5,r6,r7,r8,r9;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xy = t110.Sample(s0_s, v1.xy).xy;
  r0.z = t78.SampleLevel(s0_s, r0.xy, 0).x;
  r0.w = 1 + cb16[0].w;
  r0.z = r0.w + -r0.z;
  r0.z = cb16[0].z / r0.z;
  r1.xyz = t90.Sample(s8_s, r0.xy).xyz;
  r1.w = t2[0].val[16/4];
  r1.xyz = r1.xyz * r1.www;
  r2.xy = cb16[82].xy * r0.xy;
  r2.xyzw = t114.SampleLevel(s0_s, r2.xy, 0).xyzw;
  r1.w = cmp(r2.z >= 1);
  r2.w = cmp(r2.w < 2);
  r1.w = r1.w ? r2.w : 0;
  if (r1.w != 0) {
    r3.xy = t113.SampleLevel(s0_s, r0.xy, 0).xy;
    r3.xy = cb16[20].xx * r3.xy;
    r1.w = dot(r3.xy, r3.xy);
    r1.w = sqrt(r1.w);
    r1.w = min(cb16[20].z, r1.w);
    r2.xy = r2.xy / r2.zz;
    r2.z = min(2, r2.z);
    r2.xy = r2.xy * r2.zz;
    r2.w = 1 + r2.z;
    r2.w = min(2, r2.w);
    r3.x = (int)r2.w;
    r3.yz = cb16[66].xy * r2.xy;
    r2.w = trunc(r2.w);
    r2.w = -0.5 + r2.w;
    r2.z = r2.w / r2.z;
    r2.xy = cb16[66].xy * -r2.xy;
    r4.x = r2.z * r1.w;
    r5.xyzw = float4(0,0,0,0);
    r1.w = 0;
    while (true) {
      r3.w = cmp((int)r1.w >= (int)r3.x);
      if (r3.w != 0) break;
      r3.w = (int)r1.w;
      r6.xy = float2(0.5,-0.5) + r3.ww;
      r3.w = r6.x / r2.w;
      r6.xz = r3.yz * r3.ww + r0.xy;
      r7.xy = t113.SampleLevel(s0_s, r6.xz, 0).xy;
      r7.xy = cb16[20].xx * r7.xy;
      r4.w = dot(r7.xy, r7.xy);
      r4.w = sqrt(r4.w);
      r4.w = min(cb16[20].z, r4.w);
      r6.w = t77.SampleLevel(s0_s, r6.xz, 0).x;
      r6.w = -r6.w + r0.w;
      r6.w = cb16[0].z / r6.w;
      r7.x = 1 + -r4.w;
      r7.x = saturate(8 * r7.x);
      r7.x = 1 + -r7.x;
      r4.y = r4.w * r2.z;
      r7.y = r6.w + -r0.z;
      r7.yz = saturate(r7.yy * float2(1,-1) + float2(0.5,0.5));
      r6.y = max(0, r6.y);
      r8.xy = saturate(-r6.yy + r4.xy);
      r4.y = dot(r7.yz, r8.xy);
      r4.y = r7.x * r4.y;
      r7.xyz = t94.SampleLevel(s1_s, r6.xz, 0).xyz;
      r6.xz = r2.xy * r3.ww + r0.xy;
      r8.xy = t113.SampleLevel(s0_s, r6.xz, 0).xy;
      r8.xy = cb16[20].xx * r8.xy;
      r3.w = dot(r8.xy, r8.xy);
      r3.w = sqrt(r3.w);
      r3.w = min(cb16[20].z, r3.w);
      r7.w = t77.SampleLevel(s0_s, r6.xz, 0).x;
      r7.w = -r7.w + r0.w;
      r7.w = cb16[0].z / r7.w;
      r8.x = 1 + -r3.w;
      r8.x = saturate(8 * r8.x);
      r8.x = 1 + -r8.x;
      r4.z = r3.w * r2.z;
      r8.y = r7.w + -r0.z;
      r8.yz = saturate(r8.yy * float2(1,-1) + float2(0.5,0.5));
      r9.xy = saturate(-r6.yy + r4.xz);
      r4.z = dot(r8.yz, r9.xy);
      r4.z = r8.x * r4.z;
      r6.xyz = t94.SampleLevel(s1_s, r6.xz, 0).xyz;
      r6.w = cmp(r7.w < r6.w);
      r3.w = cmp(r4.w < r3.w);
      r4.w = r3.w ? r6.w : 0;
      r8.w = r4.w ? r4.z : r4.y;
      r3.w = (int)r3.w | (int)r6.w;
      r3.w = (int)r3.w | (int)r4.w;
      r9.w = r3.w ? r4.z : r4.y;
      r9.xyz = r9.www * r6.xyz;
      r6.xyzw = r9.xyzw + r5.xyzw;
      r8.xyz = r8.www * r7.xyz;
      r5.xyzw = r6.xyzw + r8.xyzw;
      r1.w = (int)r1.w + 1;
    }
    r0.w = (uint)r3.x << 1;
    r0.w = (int)r0.w;
    r2.xyzw = r5.xyzw / r0.wwww;
  } else {
    r2.xyzw = float4(0,0,0,0);
  }
  r0.w = 1 + -r2.w;
  r1.xyz = r0.www * r1.xyz + r2.xyz;
  r2.xyzw = t95.SampleLevel(s1_s, r0.xy, 0).xyzw;
  r0.w = 1 + -r2.w;
  r1.xyz = r0.www * r1.xyz + r2.xyz;
  r2.xyz = t116.Load(float4(0,0,0,0)).xyz;
  r3.xyzw = t116.Load(float4(1,1,1,1)).xyzw;
  r0.w = t44.Load(float4(0,0,0,0)).x;
  r4.xyz = r1.xyz * r0.www;
  r1.w = dot(r4.xyz, float3(0.300000012,0.589999974,0.109999999));
  r1.w = 0.0399999991 + r1.w;
  r1.w = 0.0399999991 / r1.w;
  if (cb16[64].x != 0) {
    r4.xyzw = t109.Sample(s8_s, v1.xy).xyzw;
    r2.w = 9.99999975e-05 + r4.w;
    r2.w = cmp(r2.w >= 1);
    r4.w = 1 + -r4.w;
    r5.xyz = r1.xyz * r4.www + r4.xyz;
    r1.xyz = r2.www ? r4.xyz : r5.xyz;
  } else {
    r2.w = 0;
  }
  r1.xyz = r1.xyz * r0.www;
  r1.xyz = min(float3(65504,65504,65504), r1.xyz);
  if (r2.w == 0) {
    if (cb16[73].x != 0) {
      r4.xyz = t81.Sample(s2_s, r0.xy).xyz;
      r4.xyz = r4.xyz * r0.www;
      r0.w = dot(r4.xyz, float3(0.300000012,0.589999974,0.109999999));
      r0.w = max(cb16[75].z, r0.w);
      r0.w = min(cb16[75].w, r0.w);
      r4.x = cb16[75].x + r0.w;
      r4.x = log2(r4.x);
      r4.x = cb16[73].y * r4.x;
      r4.x = r4.x * 0.693147182 + cb16[73].z;
      r4.x = -10 + r4.x;
      r0.w = cb16[75].y * r0.w + r4.x;
      r0.w = cb16[68].w + r0.w;
      r0.w = max(cb16[69].x, r0.w);
      r0.w = min(cb16[69].y, r0.w);
      r4.x = cb16[69].z * abs(r0.w);
      r4.y = cmp(0 < r0.w);
      r4.z = cmp(r0.w < 0);
      r4.y = (int)-r4.y + (int)r4.z;
      r4.y = (int)r4.y;
      r0.w = r4.x * r4.y + r0.w;
      r0.w = max(cb16[69].x, r0.w);
      r0.w = min(cb16[69].y, r0.w);
      r4.x = saturate(cb16[73].x);
      r0.w = -v2.x + r0.w;
      r0.w = r4.x * r0.w + v2.x;
      r0.w = exp2(r0.w);
    } else {
      r0.w = v1.z;
    }
    r4.xy = -cb16[53].xy + v1.xy;
    r5.x = dot(cb16[55].xy, r4.xy);
    r5.y = dot(cb16[55].zw, r4.xy);
    r4.xy = cb16[53].zw * r5.xy;
    r4.x = dot(r4.xy, r4.xy);
    r4.x = -cb16[56].x + r4.x;
    r4.x = cb16[56].w * r4.x;
    r4.x = max(0, r4.x);
    r4.y = cmp(r4.x < 1);
    r4.z = -10 * r4.x;
    r4.z = exp2(r4.z);
    r4.z = 1 + -r4.z;
    r4.xw = float2(-1,-2) + r4.xx;
    r4.x = cmp(0 < r4.x);
    r4.w = 10 * r4.w;
    r4.w = exp2(r4.w);
    r4.x = r4.x ? r4.w : 0;
    r4.x = 0.998049974 + r4.x;
    r4.x = r4.y ? r4.z : r4.x;
    r4.yzw = cb16[54].xyz * r1.xyz;
    r4.yzw = r4.yzw * cb16[54].www + -r1.xyz;
    r4.xyz = r4.xxx * r4.yzw + r1.xyz;
    r1.xyz = cb16[54].www ? r4.xyz : r1.xyz;
  } else {
    r0.w = v1.z;
  }
  r4.x = saturate(cb16[60].y * v1.y);
  r4.x = saturate(cb16[57].w + r4.x);
  r4.y = saturate(-cb16[59].w + v1.y);
  r4.y = saturate(cb16[60].x * r4.y);
  r4.y = saturate(-cb16[58].w + r4.y);
  r5.xyz = cb16[59].xyz + -cb16[57].xyz;
  r4.xzw = r4.xxx * r5.xyz + cb16[57].xyz;
  r5.xyz = -cb16[59].xyz + cb16[58].xyz;
  r5.xyz = r4.yyy * r5.xyz + cb16[59].xyz;
  r5.xyz = r5.xyz + -r4.xzw;
  r4.xyz = v1.yyy * r5.xyz + r4.xzw;
  r1.xyz = r4.xyz * r1.xyz;
  if (RENODX_TONE_MAP_TYPE != 0.f) {
    const float renodx_contrast_override = (asuint(cb20[1].x) != 0u) ? cb20[2].z : r2.z;
    r1.xyz = ApplyToneMap(
        r1.xyz,
        cb20[0].w != 0.f,
        r0.w,
        cb20[1].z,
        (uint)cb20[1].x,
        renodx_contrast_override,
        r2.xyz,
        r3.xyzw);
  } else {
  r4.x = cb20[1].x ? cb20[2].z : r2.z;
  r4.y = r0.w / cb20[1].z;
  r4.yzw = r4.yyy * r1.xyz;
  r4.yzw = max(float3(0,0,0), r4.yzw);
  r5.xyz = r2.xxx * r4.yzw + r3.xxx;
  r5.xyz = r4.yzw * r5.xyz + r3.yyy;
  r6.xyz = r2.xxx * r4.yzw + r2.yyy;
  r4.yzw = r4.yzw * r6.xyz + r3.zzz;
  r4.yzw = r5.xyz / r4.yzw;
  r4.yzw = r4.yzw + -r3.www;
  r4.xyz = r4.yzw * r4.xxx;
  r4.xyz = cb20[1].zzz * r4.xyz;
  r1.xyz = r1.xyz * r0.www;
  r1.xyz = max(float3(0,0,0), r1.xyz);
  r5.xyz = r2.xxx * r1.xyz + r3.xxx;
  r5.xyz = r1.xyz * r5.xyz + r3.yyy;
  r6.xyz = r2.xxx * r1.xyz + r2.yyy;
  r1.xyz = r1.xyz * r6.xyz + r3.zzz;
  r1.xyz = r5.xyz / r1.xyz;
  r1.xyz = r1.xyz + -r3.www;
  r1.xyz = saturate(r1.xyz * r2.zzz);
  r1.xyz = cb20[0].www ? r4.xyz : r1.xyz;
  }
  if (r2.w == 0) {
    if (cb16[50].w != 0) {
      r2.xy = -cb16[49].xy + v1.xy;
      r3.x = dot(cb16[51].xy, r2.xy);
      r3.y = dot(cb16[51].zw, r2.xy);
      r2.xy = cb16[49].zw * r3.xy;
      r0.w = dot(r2.xy, r2.xy);
      r0.w = -cb16[52].x + r0.w;
      r0.w = saturate(cb16[52].w * r0.w);
r0.w = t89.Sample(s2_s, r0.wwww).w;
      r0.w = cb16[50].w * r0.w;
      r2.xyz = cb16[50].xyz + -r1.xyz;
      r1.xyz = r0.www * r2.xyz + r1.xyz;
    }
  }
  r2.xyz = cb20[2].www * r1.xyz;
  r3.xyz = log2(r1.xyz);
  r3.xyz = cb20[3].xxx * r3.xyz;
  r3.xyz = exp2(r3.xyz);
  r3.xyz = r3.xyz * cb20[3].yyy + -cb20[3].zzz;
  r4.xyz = cmp(r1.xyz < float3(0.00313080009,0.00313080009,0.00313080009));
  r2.xyz = r4.xyz ? r2.xyz : r3.xyz;
  r0.w = cmp(asint(cb20[0].w) != 0);
  r3.x = cmp(asint(cb20[0].z) == 0);
  r0.w = r0.w ? r3.x : 0;
  r1.xyz = r0.www ? r1.xyz : r2.xyz;
  r2.x = dot(float3(0.514900029,0.324400008,0.160699993), r1.xyz);
  r2.y = dot(float3(0.265399992,0.670400023,0.064199999), r1.xyz);
  r2.z = dot(float3(0.0248000007,0.124799997,0.850399971), r1.xyz);
  r2.xyz = max(float3(0.00999999978,0,0), r2.xyz);
  r2.z = r2.y + r2.z;
  r2.x = r2.z / r2.x;
  r2.x = 1 + r2.x;
  r2.x = r2.x * 1.33000004 + -1.67999995;
  r2.x = r2.y * r2.x;
  r2.xyz = cb16[83].xyz * r2.xxx;
  r2.xyz = saturate(cb16[83].www * r2.xyz);
  r1.w = saturate(r1.w * cb16[84].x + cb16[84].y);
  r2.xyz = r2.xyz + -r1.xyz;
  r1.xyz = r1.www * r2.xyz + r1.xyz;
  if (cb16[86].w != 0) {
    r2.xy = cb16[87].zy + -cb16[87].wx;
    r2.xy = v1.yx * r2.xy + cb16[87].wx;
    r3.xy = float2(-0.5,-0.5) + v1.xy;
    r3.xy = cb16[86].zz * r3.xy;
    r2.xy = r3.xy / r2.xy;
    r2.xy = -cb16[86].xy + r2.xy;
    r2.xy = float2(0.5,0.5) + r2.xy;
    r2.xyz = t111.Sample(s2_s, r2.xy).xyz;
    r2.xyz = r2.xyz + -r1.xyz;
    r1.xyz = cb16[86].www * r2.xyz + r1.xyz;
  }
  if (r2.w == 0) {
    r1.w = cmp(asint(cb20[1].y) == 0);
    r0.w = r0.w ? r1.w : 0;
    r1.w = max(r1.y, r1.z);
    r1.w = max(r1.x, r1.w);
    r1.w = max(9.99999975e-05, r1.w);
    r2.x = cmp(cb20[1].w < r1.w);
    r2.y = r1.w * cb20[2].x + cb20[2].y;
    r2.x = r2.x ? r2.y : r1.w;
    r1.w = r2.x / r1.w;
    r0.w = r0.w ? 1 : r1.w;
    r2.xyzw = r1.zzxy * r0.wwww;
    r3.xyw = float3(14.9998999,0.9375,0.05859375) * r2.xwz;
    r1.w = floor(r3.x);
    r2.x = r2.y * 15 + -r1.w;
    r3.x = r1.w * 0.0625 + r3.w;
    r3.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r3.xyxy;
    r2.yzw = t106.Sample(s2_s, r3.xy).xyz;
    r3.xyz = t106.Sample(s2_s, r3.zw).xyz;
    r3.xyz = r3.xyz + -r2.yzw;
    r2.xyz = r2.xxx * r3.xyz + r2.yzw;
    r1.w = t118[0].val[0/4];
    r1.w = cmp(0 < (int)r1.w);
    if (r1.w != 0) {
      r3.x = t118[0].val[16/4];
      r3.y = t118[0].val[16/4+1];
      r3.z = t118[0].val[16/4+2];
      r3.w = t118[0].val[16/4+3];
      r4.x = t118[0].val[32/4];
      r4.y = t118[0].val[32/4+1];
      r4.z = t118[0].val[32/4+2];
      r4.w = t118[0].val[32/4+3];
      r5.x = t118[0].val[48/4];
      r5.y = t118[0].val[48/4+1];
      r5.zw = -r3.xz + r0.zz;
      r3.xy = saturate(r5.zw * r3.yw);
      r1.w = 1 + -r3.y;
      r2.w = cmp(r0.z < r3.z);
      r1.w = r2.w ? r3.x : r1.w;
      r1.w = saturate(r1.w + r4.x);
      r3.xyw = float3(14.9998999,0.9375,0.05859375) * r2.zyx;
      r2.w = floor(r3.x);
      r3.z = r2.z * 15 + -r2.w;
      r3.x = r2.w * 0.0625 + r3.w;
      r6.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r3.xyxy;
      r3.xyw = t100.Sample(s2_s, r6.xy).xyz;
      r6.xyz = t100.Sample(s2_s, r6.zw).xyz;
      r6.xyz = r6.xyz + -r3.xyw;
      r3.xyz = r3.zzz * r6.xyz + r3.xyw;
      r3.xyz = r3.xyz + -r2.xyz;
      r3.xyz = r1.www * r3.xyz + r2.xyz;
      r4.xy = -r4.yw + r0.zz;
      r1.w = saturate(r4.x * r4.z);
      r2.w = saturate(r4.y * r5.x);
      r2.w = 1 + -r2.w;
      r0.z = cmp(r0.z < r4.w);
      r0.z = r0.z ? r1.w : r2.w;
      r0.z = saturate(r0.z + r5.y);
      r4.xyw = float3(14.9998999,0.9375,0.05859375) * r3.zyx;
      r1.w = floor(r4.x);
      r2.w = r3.z * 15 + -r1.w;
      r4.x = r1.w * 0.0625 + r4.w;
      r4.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r4.xyxy;
      r5.xyz = t101.Sample(s2_s, r4.xy).xyz;
      r4.xyz = t101.Sample(s2_s, r4.zw).xyz;
      r4.xyz = r4.xyz + -r5.xyz;
      r4.xyz = r2.www * r4.xyz + r5.xyz;
      r4.xyz = r4.xyz + -r3.xyz;
      r4.xyz = r4.xyz * r0.zzz;
      r0.xyz = t107.Sample(s2_s, r0.xy).xyz;
      r0.x = dot(r0.xyz, float3(0.212599993,0.715200007,0.0722000003));
      r2.xyz = r0.xxx * r4.xyz + r3.xyz;
    }
    r1.xyz = r2.xyz / r0.www;
  }
  r0.w = dot(r1.xyz, float3(0.298999995,0.587000012,0.114));
  r1.w = max(r1.y, r1.z);
  r1.w = max(r1.x, r1.w);
  r2.xyz = cb16[41].www ? r1.xyz : r1.www;
  r2.xyz = -cb16[42].xyz + r2.xyz;
  r2.xyz = saturate(cb16[41].xyz * r2.xyz);
  r2.xyz = log2(r2.xyz);
  r2.xyz = cb16[42].www * r2.xyz;
  r2.xyz = exp2(r2.xyz);
  r3.xyz = cb16[40].xyz + -cb16[39].xyz;
  r2.xyz = r2.xyz * r3.xyz + cb16[39].xyz;
  r3.xy = (uint2)v0.xy;
  r1.w = t3[0].val[1840/4];
  r3.xy = (int2)r3.xy & int2(63,63);
  r3.z = (int)r1.w & 31;
  r3.w = 0;
  r1.w = t25.Load(r3.xyzw).x;
  r1.w = r1.w * 2 + -1;
  r2.w = cmp(0 < r1.w);
  r3.x = cmp(r1.w < 0);
  r2.w = (int)-r2.w + (int)r3.x;
  r2.w = (int)r2.w;
  r3.x = 1 + -abs(r1.w);
  r3.x = sqrt(r3.x);
  r3.x = 1 + -r3.x;
  r2.w = r3.x * r2.w;
  r1.w = cb20[0].w ? r2.w : r1.w;
  r0.xyz = r1.www * r2.xyz + r1.xyz;
  r1.xyzw = saturate(r0.xyzw);
  o0.xyzw = cb20[0].wwww ? r0.xyzw : r1.xyzw;
  o0.xyz = ApplyGradingAndDisplayMap(o0.xyz, v1.xy);
  return o0;
}