/*
 * DX12 replacement for shader 0x20270B14 (ps_5_1) -- RDR2 tone-mapping pass.
 *
 * Generated by tools/mech-port.mjs from a 3DMigoto decompilation of the game's
 * own DX12 bytecode (captures/msasm/0x20270B14.ps_5_1.asm), then repaired
 * where the decompiler could not represent an instruction. The arithmetic,
 * register bindings and structured-buffer strides are therefore the game's, not
 * a re-derivation, which is why this file is generated rather than written by
 * hand: retyping the decompilation would only add opportunities for error.
 *
 * Not translated from the Vulkan mod's tonemap_*.frag.vk.glsl. The two renderers
 * differ in this pass; the Vulkan source is used only to decide what RenoDX
 * changes, which is the grading call spliced in at the end.
 *
 * The only behavioural changes are:
 *   - the RenoDX injection constant buffer is added (b13, space50), and
 *   - ApplyGradingAndDisplayMap() runs on the final colour.
 * Everything else, including both tone-map branches and the select between
 * them, is the original arithmetic, so ToneMapper = Vanilla is preserved.
 *
 * Bindings are verified to match the original by tools/verify-bindings.mjs.
 *
 * Unverified in game: this has only been validated by compilation and by
 * comparing the binding slots it reads against the original.
 */
#include "../shared.h"
#include "../tonemap/tonemap.hlsli"

// ---- Created with 3Dmigoto v1.4.9 on Fri Sep 18 01:27:32 2026
struct t118_t {
  float val[59];
};
StructuredBuffer<t118_t> t118 : register(t118);

Buffer<float4> t116 : register(t116);

Texture2D<float4> t111 : register(t111);

Texture2D<float4> t110 : register(t110);

Texture2D<float4> t109 : register(t109);

Texture2D<float4> t107 : register(t107);

Texture2D<float4> t106 : register(t106);

Texture2D<float4> t101 : register(t101);

Texture2D<float4> t100 : register(t100);

Texture1D<float4> t89 : register(t89);

Texture2D<float4> t90 : register(t90);

Texture2D<float4> t81 : register(t81);

Texture2D<float4> t78 : register(t78);

Texture2D<float4> t44 : register(t44);

Texture2DArray<float4> t25 : register(t25);

struct t3_t {
  float val[476];
};
StructuredBuffer<t3_t> t3 : register(t3);

struct t2_t {
  float val[501];
};
StructuredBuffer<t2_t> t2 : register(t2);

SamplerState s8_s : register(s8);

SamplerState s2_s : register(s2);

SamplerState s0_s : register(s0);

cbuffer cb20 : register(b20)
{
  float4 cb20[5];
}

cbuffer cb16 : register(b16)
{
  float4 cb16[88];
}




// 3Dmigoto declarations
#define cmp -


float4 main(
  float4 v0 : SV_Position,
  float4 v1 : TEXCOORD0,
  float v2 : TEXCOORD1) : SV_Target0
{
  float4 o0;
  float4 r0,r1,r2,r3,r4,r5,r6;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xy = t110.Sample(s0_s, v1.xy).xy;
  r1.xyz = t90.Sample(s8_s, r0.xy).xyz;
  r0.z = t2[0].val[16/4];
  r1.xyz = r1.xyz * r0.zzz;
  r2.xyz = t116.Load(float4(0,0,0,0)).xyz;
  r3.xyzw = t116.Load(float4(1,1,1,1)).xyzw;
  r0.z = t44.Load(float4(0,0,0,0)).x;
  r4.xyz = r1.xyz * r0.zzz;
  r0.w = dot(r4.xyz, float3(0.300000012,0.589999974,0.109999999));
  r0.w = 0.0399999991 + r0.w;
  r0.w = 0.0399999991 / r0.w;
  if (cb16[64].x != 0) {
    r4.xyzw = t109.Sample(s8_s, v1.xy).xyzw;
    r1.w = 9.99999975e-05 + r4.w;
    r1.w = cmp(r1.w >= 1);
    r2.w = 1 + -r4.w;
    r5.xyz = r1.xyz * r2.www + r4.xyz;
    r1.xyz = r1.www ? r4.xyz : r5.xyz;
  } else {
    r1.w = 0;
  }
  r1.xyz = r1.xyz * r0.zzz;
  r1.xyz = min(float3(65504,65504,65504), r1.xyz);
  if (r1.w == 0) {
    if (cb16[73].x != 0) {
      r4.xyz = t81.Sample(s2_s, r0.xy).xyz;
      r4.xyz = r4.xyz * r0.zzz;
      r0.z = dot(r4.xyz, float3(0.300000012,0.589999974,0.109999999));
      r0.z = max(cb16[75].z, r0.z);
      r0.z = min(cb16[75].w, r0.z);
      r2.w = cb16[75].x + r0.z;
      r2.w = log2(r2.w);
      r2.w = cb16[73].y * r2.w;
      r2.w = r2.w * 0.693147182 + cb16[73].z;
      r2.w = -10 + r2.w;
      r0.z = cb16[75].y * r0.z + r2.w;
      r0.z = cb16[68].w + r0.z;
      r0.z = max(cb16[69].x, r0.z);
      r0.z = min(cb16[69].y, r0.z);
      r2.w = cb16[69].z * abs(r0.z);
      r4.x = cmp(0 < r0.z);
      r4.y = cmp(r0.z < 0);
      r4.x = (int)-r4.x + (int)r4.y;
      r4.x = (int)r4.x;
      r0.z = r2.w * r4.x + r0.z;
      r0.z = max(cb16[69].x, r0.z);
      r0.z = min(cb16[69].y, r0.z);
      r2.w = saturate(cb16[73].x);
      r0.z = -v2.x + r0.z;
      r0.z = r2.w * r0.z + v2.x;
      r0.z = exp2(r0.z);
    } else {
      r0.z = v1.z;
    }
    r4.xy = -cb16[53].xy + v1.xy;
    r5.x = dot(cb16[55].xy, r4.xy);
    r5.y = dot(cb16[55].zw, r4.xy);
    r4.xy = cb16[53].zw * r5.xy;
    r2.w = dot(r4.xy, r4.xy);
    r2.w = -cb16[56].x + r2.w;
    r2.w = cb16[56].w * r2.w;
    r2.w = max(0, r2.w);
    r4.x = cmp(r2.w < 1);
    r4.y = -10 * r2.w;
    r4.y = exp2(r4.y);
    r4.y = 1 + -r4.y;
    r4.zw = float2(-1,-2) + r2.ww;
    r2.w = cmp(0 < r4.z);
    r4.z = 10 * r4.w;
    r4.z = exp2(r4.z);
    r2.w = r2.w ? r4.z : 0;
    r2.w = 0.998049974 + r2.w;
    r2.w = r4.x ? r4.y : r2.w;
    r4.xyz = cb16[54].xyz * r1.xyz;
    r4.xyz = r4.xyz * cb16[54].www + -r1.xyz;
    r4.xyz = r2.www * r4.xyz + r1.xyz;
    r1.xyz = cb16[54].www ? r4.xyz : r1.xyz;
  } else {
    r0.z = v1.z;
  }
  r2.w = saturate(cb16[60].y * v1.y);
  r2.w = saturate(cb16[57].w + r2.w);
  r4.x = saturate(-cb16[59].w + v1.y);
  r4.x = saturate(cb16[60].x * r4.x);
  r4.x = saturate(-cb16[58].w + r4.x);
  r4.yzw = cb16[59].xyz + -cb16[57].xyz;
  r4.yzw = r2.www * r4.yzw + cb16[57].xyz;
  r5.xyz = -cb16[59].xyz + cb16[58].xyz;
  r5.xyz = r4.xxx * r5.xyz + cb16[59].xyz;
  r5.xyz = r5.xyz + -r4.yzw;
  r4.xyz = v1.yyy * r5.xyz + r4.yzw;
  r1.xyz = r4.xyz * r1.xyz;
  if (RENODX_TONE_MAP_TYPE != 0.f) {
    const float renodx_contrast_override = (asuint(cb20[1].x) != 0u) ? cb20[2].z : r2.z;
    r1.xyz = ApplyToneMap(
        r1.xyz,
        cb20[0].w != 0.f,
        r0.z,
        cb20[1].z,
        (uint)cb20[1].x,
        renodx_contrast_override,
        r2.xyz,
        r3.xyzw);
  } else {
  r2.w = cb20[1].x ? cb20[2].z : r2.z;
  r4.x = r0.z / cb20[1].z;
  r4.xyz = r4.xxx * r1.xyz;
  r4.xyz = max(float3(0,0,0), r4.xyz);
  r5.xyz = r2.xxx * r4.xyz + r3.xxx;
  r5.xyz = r4.xyz * r5.xyz + r3.yyy;
  r6.xyz = r2.xxx * r4.xyz + r2.yyy;
  r4.xyz = r4.xyz * r6.xyz + r3.zzz;
  r4.xyz = r5.xyz / r4.xyz;
  r4.xyz = r4.xyz + -r3.www;
  r4.xyz = r4.xyz * r2.www;
  r4.xyz = cb20[1].zzz * r4.xyz;
  r1.xyz = r1.xyz * r0.zzz;
  r1.xyz = max(float3(0,0,0), r1.xyz);
  r5.xyz = r2.xxx * r1.xyz + r3.xxx;
  r5.xyz = r1.xyz * r5.xyz + r3.yyy;
  r2.xyw = r2.xxx * r1.xyz + r2.yyy;
  r1.xyz = r1.xyz * r2.xyw + r3.zzz;
  r1.xyz = r5.xyz / r1.xyz;
  r1.xyz = r1.xyz + -r3.www;
  r1.xyz = saturate(r1.xyz * r2.zzz);
  r1.xyz = cb20[0].www ? r4.xyz : r1.xyz;
  }
  if (r1.w == 0) {
    if (cb16[50].w != 0) {
      r2.xy = -cb16[49].xy + v1.xy;
      r3.x = dot(cb16[51].xy, r2.xy);
      r3.y = dot(cb16[51].zw, r2.xy);
      r2.xy = cb16[49].zw * r3.xy;
      r0.z = dot(r2.xy, r2.xy);
      r0.z = -cb16[52].x + r0.z;
      r0.z = saturate(cb16[52].w * r0.z);
r0.z = t89.Sample(s2_s, r0.zzzz).w;
      r0.z = cb16[50].w * r0.z;
      r2.xyz = cb16[50].xyz + -r1.xyz;
      r1.xyz = r0.zzz * r2.xyz + r1.xyz;
    }
  }
  r2.xyz = cb20[2].www * r1.xyz;
  r3.xyz = log2(r1.xyz);
  r3.xyz = cb20[3].xxx * r3.xyz;
  r3.xyz = exp2(r3.xyz);
  r3.xyz = r3.xyz * cb20[3].yyy + -cb20[3].zzz;
  r4.xyz = cmp(r1.xyz < float3(0.00313080009,0.00313080009,0.00313080009));
  r2.xyz = r4.xyz ? r2.xyz : r3.xyz;
  r0.z = cmp(asint(cb20[0].w) != 0);
  r2.w = cmp(asint(cb20[0].z) == 0);
  r0.z = r0.z ? r2.w : 0;
  r1.xyz = r0.zzz ? r1.xyz : r2.xyz;
  r2.x = dot(float3(0.514900029,0.324400008,0.160699993), r1.xyz);
  r2.y = dot(float3(0.265399992,0.670400023,0.064199999), r1.xyz);
  r2.z = dot(float3(0.0248000007,0.124799997,0.850399971), r1.xyz);
  r2.xyz = max(float3(0.00999999978,0,0), r2.xyz);
  r2.z = r2.y + r2.z;
  r2.x = r2.z / r2.x;
  r2.x = 1 + r2.x;
  r2.x = r2.x * 1.33000004 + -1.67999995;
  r2.x = r2.y * r2.x;
  r2.xyz = cb16[83].xyz * r2.xxx;
  r2.xyz = saturate(cb16[83].www * r2.xyz);
  r0.w = saturate(r0.w * cb16[84].x + cb16[84].y);
  r2.xyz = r2.xyz + -r1.xyz;
  r1.xyz = r0.www * r2.xyz + r1.xyz;
  if (cb16[86].w != 0) {
    r2.xy = cb16[87].zy + -cb16[87].wx;
    r2.xy = v1.yx * r2.xy + cb16[87].wx;
    r2.zw = float2(-0.5,-0.5) + v1.xy;
    r2.zw = cb16[86].zz * r2.zw;
    r2.xy = r2.zw / r2.xy;
    r2.xy = -cb16[86].xy + r2.xy;
    r2.xy = float2(0.5,0.5) + r2.xy;
    r2.xyz = t111.Sample(s2_s, r2.xy).xyz;
    r2.xyz = r2.xyz + -r1.xyz;
    r1.xyz = cb16[86].www * r2.xyz + r1.xyz;
  }
  if (r1.w == 0) {
    r0.w = cmp(asint(cb20[1].y) == 0);
    r0.z = r0.w ? r0.z : 0;
    r0.w = max(r1.y, r1.z);
    r0.w = max(r1.x, r0.w);
    r0.w = max(9.99999975e-05, r0.w);
    r1.w = cmp(cb20[1].w < r0.w);
    r2.x = r0.w * cb20[2].x + cb20[2].y;
    r1.w = r1.w ? r2.x : r0.w;
    r0.w = r1.w / r0.w;
    r0.z = r0.z ? 1 : r0.w;
    r2.xyzw = r1.zzxy * r0.zzzz;
    r3.xyw = float3(14.9998999,0.9375,0.05859375) * r2.xwz;
    r0.w = floor(r3.x);
    r1.w = r2.y * 15 + -r0.w;
    r3.x = r0.w * 0.0625 + r3.w;
    r2.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r3.xyxy;
    r3.xyz = t106.Sample(s2_s, r2.xy).xyz;
    r2.xyz = t106.Sample(s2_s, r2.zw).xyz;
    r2.xyz = r2.xyz + -r3.xyz;
    r2.xyz = r1.www * r2.xyz + r3.xyz;
    r0.w = t118[0].val[0/4];
    r0.w = cmp(0 < (int)r0.w);
    if (r0.w != 0) {
      r0.w = t78.SampleLevel(s0_s, r0.xy, 0).x;
      r1.w = 1 + cb16[0].w;
      r0.w = r1.w + -r0.w;
      r0.w = cb16[0].z / r0.w;
      r3.x = t118[0].val[16/4];
      r3.y = t118[0].val[16/4+1];
      r3.z = t118[0].val[16/4+2];
      r3.w = t118[0].val[16/4+3];
      r4.x = t118[0].val[32/4];
      r4.y = t118[0].val[32/4+1];
      r4.z = t118[0].val[32/4+2];
      r4.w = t118[0].val[32/4+3];
      r5.x = t118[0].val[48/4];
      r5.y = t118[0].val[48/4+1];
      r5.zw = -r3.xz + r0.ww;
      r3.xy = saturate(r5.zw * r3.yw);
      r1.w = 1 + -r3.y;
      r2.w = cmp(r0.w < r3.z);
      r1.w = r2.w ? r3.x : r1.w;
      r1.w = saturate(r1.w + r4.x);
      r3.xyw = float3(14.9998999,0.9375,0.05859375) * r2.zyx;
      r2.w = floor(r3.x);
      r3.z = r2.z * 15 + -r2.w;
      r3.x = r2.w * 0.0625 + r3.w;
      r6.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r3.xyxy;
      r3.xyw = t100.Sample(s2_s, r6.xy).xyz;
      r6.xyz = t100.Sample(s2_s, r6.zw).xyz;
      r6.xyz = r6.xyz + -r3.xyw;
      r3.xyz = r3.zzz * r6.xyz + r3.xyw;
      r3.xyz = r3.xyz + -r2.xyz;
      r3.xyz = r1.www * r3.xyz + r2.xyz;
      r4.xy = -r4.yw + r0.ww;
      r1.w = saturate(r4.x * r4.z);
      r2.w = saturate(r4.y * r5.x);
      r2.w = 1 + -r2.w;
      r0.w = cmp(r0.w < r4.w);
      r0.w = r0.w ? r1.w : r2.w;
      r0.w = saturate(r0.w + r5.y);
      r4.xyw = float3(14.9998999,0.9375,0.05859375) * r3.zyx;
      r1.w = floor(r4.x);
      r2.w = r3.z * 15 + -r1.w;
      r4.x = r1.w * 0.0625 + r4.w;
      r4.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r4.xyxy;
      r5.xyz = t101.Sample(s2_s, r4.xy).xyz;
      r4.xyz = t101.Sample(s2_s, r4.zw).xyz;
      r4.xyz = r4.xyz + -r5.xyz;
      r4.xyz = r2.www * r4.xyz + r5.xyz;
      r4.xyz = r4.xyz + -r3.xyz;
      r4.xyz = r4.xyz * r0.www;
      r0.xyw = t107.Sample(s2_s, r0.xy).xyz;
      r0.x = dot(r0.xyw, float3(0.212599993,0.715200007,0.0722000003));
      r2.xyz = r0.xxx * r4.xyz + r3.xyz;
    }
    r1.xyz = r2.xyz / r0.zzz;
  }
  r0.w = dot(r1.xyz, float3(0.298999995,0.587000012,0.114));
  r1.w = max(r1.y, r1.z);
  r1.w = max(r1.x, r1.w);
  r2.xyz = cb16[41].www ? r1.xyz : r1.www;
  r2.xyz = -cb16[42].xyz + r2.xyz;
  r2.xyz = saturate(cb16[41].xyz * r2.xyz);
  r2.xyz = log2(r2.xyz);
  r2.xyz = cb16[42].www * r2.xyz;
  r2.xyz = exp2(r2.xyz);
  r3.xyz = cb16[40].xyz + -cb16[39].xyz;
  r2.xyz = r2.xyz * r3.xyz + cb16[39].xyz;
  r3.xy = (uint2)v0.xy;
  r1.w = t3[0].val[1840/4];
  r3.xy = (int2)r3.xy & int2(63,63);
  r3.z = (int)r1.w & 31;
  r3.w = 0;
  r1.w = t25.Load(r3.xyzw).x;
  r1.w = r1.w * 2 + -1;
  r2.w = cmp(0 < r1.w);
  r3.x = cmp(r1.w < 0);
  r2.w = (int)-r2.w + (int)r3.x;
  r2.w = (int)r2.w;
  r3.x = 1 + -abs(r1.w);
  r3.x = sqrt(r3.x);
  r3.x = 1 + -r3.x;
  r2.w = r3.x * r2.w;
  r1.w = cb20[0].w ? r2.w : r1.w;
  r0.xyz = r1.www * r2.xyz + r1.xyz;
  r1.xyzw = saturate(r0.xyzw);
  o0.xyzw = cb20[0].wwww ? r0.xyzw : r1.xyzw;
  o0.xyz = ApplyGradingAndDisplayMap(o0.xyz, v1.xy);
  return o0;
}