/*
 * DX12 replacement for shader 0x307A8225 (ps_5_1) -- RDR2 HDR output / PQ encode pass.
 *
 * Generated by tools/output-port.mjs from a 3DMigoto decompilation of the game's
 * own DX12 bytecode (captures/msasm/0x307A8225.ps_5_1.asm), so the resource
 * bindings and everything outside the patched encoder are the game's.
 *
 * RDR2 emits many variants of this pass -- some sample a colour texture, some
 * take the colour from an interpolator, some multiply by a second texture's
 * alpha, one discards below an alpha threshold, one applies a colour-space LUT
 * first. Only the shared tail is patched: the BT.709 -> BT.2020 conversion and
 * the PQ encoder. Each variant's own input stage is left exactly as it was.
 *
 * The only behavioural changes, matching the Vulkan mod's output shaders:
 *   - GammaSafe() runs on the linear colour before the BT.2020 conversion, and
 *   - PQEncodeUI() drives the encoder when a RenoDX tone mapper is active,
 *     instead of the game's own brightness factors.
 * The original encoder arithmetic is kept in the else branch, so ToneMapper =
 * Vanilla is exact.
 *
 * Bindings are verified against the original by tools/verify-bindings.mjs.
 *
 * Unverified in game: validated only by compilation and by comparing the binding
 * slots it reads against the original.
 */
#include "../shared.h"
#include "../output/output.hlsli"

// ---- Created with 3Dmigoto v1.4.9 on Fri Sep 18 01:27:32 2026
Texture3D<float4> t111 : register(t111);

Texture2D<float4> t91 : register(t91);

Texture2DArray<float4> t27 : register(t27);

struct t3_t {
  float val[476];
};
StructuredBuffer<t3_t> t3 : register(t3);

SamplerState s2_s : register(s2);

SamplerState s0_s : register(s0);

cbuffer cb18 : register(b18)
{
  float4 cb18[5];
}

cbuffer cb17 : register(b17)
{
  float4 cb17[9];
}




// 3Dmigoto declarations
#define cmp -


void main(
  float4 v0 : SV_Position0,
  float4 v1 : COLOR0,
  float2 v2 : TEXCOORD0,
  out float4 o0 : SV_Target0)
{
  float4 r0,r1,r2,r3;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xyzw = t91.SampleLevel(s0_s, v2.xy, 0).xyzw;
  r1.x = cmp(asint(cb18[0].w) != 0);
  r1.y = cmp(asint(cb18[0].z) == 0);
  r1.x = r1.y ? r1.x : 0;
  r1.yzw = r0.xyz / cb18[2].www;
  r2.xyz = cb18[3].zzz + r0.xyz;
  r2.xyz = r2.xyz / cb18[3].yyy;
  r2.w = 1 / cb18[3].x;
  r2.xyz = log2(r2.xyz);
  r2.xyz = r2.www * r2.xyz;
  r2.xyz = exp2(r2.xyz);
  r2.w = 0.00313080009 / cb18[2].w;
  r3.xyz = cmp(r0.xyz < r2.www);
  r1.yzw = r3.xyz ? r1.yzw : r2.xyz;
  r1.xyz = r1.xxx ? r0.xyz : r1.yzw;
  if (cb18[4].x != 0) {
    r1.w = (uint)cb17[8].x;
    r2.x = cmp((int)r1.w == 1);
    if (r2.x != 0) {
      r2.xyz = float3(1.00000001e-07,1.00000001e-07,1.00000001e-07) + r1.xyz;
      r2.xyz = log2(r2.xyz);
      r1.xyz = r2.xyz * cb17[8].yyy + cb17[8].zzz;
    } else {
      r1.w = cmp((int)r1.w == 2);
      if (r1.w != 0) {
        r2.xyz = r1.xyz * cb17[8].yyy + cb17[8].zzz;
        r2.xyz = float3(9.99999975e-05,9.99999975e-05,9.99999975e-05) * r2.xyz;
        r2.xyz = log2(r2.xyz);
        r2.xyz = float3(0.159301758,0.159301758,0.159301758) * r2.xyz;
        r2.xyz = exp2(r2.xyz);
        r3.xyzw = r2.xxyy * float4(18.8515625,18.6875,18.8515625,18.6875) + float4(0.8359375,1,0.8359375,1);
        r2.xy = r3.xz / r3.yw;
        r2.xy = log2(r2.xy);
        r2.xy = float2(78.84375,78.84375) * r2.xy;
        r1.xy = exp2(r2.xy);
        r2.xy = r2.zz * float2(18.8515625,18.6875) + float2(0.8359375,1);
        r1.w = r2.x / r2.y;
        r1.w = log2(r1.w);
        r1.w = 78.84375 * r1.w;
        r1.z = exp2(r1.w);
      }
    }
    r1.xyz = t111.SampleLevel(s2_s, r1.xyz, 0).xyz;
  }
  r1.xyz = GammaSafe(r1.xyz);
  r1.w = dot(float3(0.627403975,0.329281986,0.0433136001), r1.xyz);
  r2.x = dot(float3(0.0690969974,0.919539988,0.0113612004), r1.xyz);
  r1.x = dot(float3(0.0163915996,0.088013202,0.895595014), r1.xyz);
  if (RENODX_TONE_MAP_TYPE != 0.f) {
    r0.xyz = PQEncodeUI(r1.xyz);
  } else {
  r1.xy = cb18[0].xx * r1.xw;
  r1.z = cb18[0].x * r2.x;
  r1.xyz = r1.xyz / cb18[3].www;
  r1.y = log2(abs(r1.y));
  r1.y = 0.159301758 * r1.y;
  r1.y = exp2(r1.y);
  r1.yw = r1.yy * float2(18.8515625,18.6875) + float2(0.8359375,1);
  r1.y = r1.y / r1.w;
  r1.y = log2(r1.y);
  r1.y = 78.84375 * r1.y;
  r0.x = exp2(r1.y);
  r1.y = log2(abs(r1.z));
  r1.y = 0.159301758 * r1.y;
  r1.y = exp2(r1.y);
  r1.yz = r1.yy * float2(18.8515625,18.6875) + float2(0.8359375,1);
  r1.y = r1.y / r1.z;
  r1.y = log2(r1.y);
  r1.y = 78.84375 * r1.y;
  r0.y = exp2(r1.y);
  r1.x = log2(abs(r1.x));
  r1.x = 0.159301758 * r1.x;
  r1.x = exp2(r1.x);
  r1.xy = r1.xx * float2(18.8515625,18.6875) + float2(0.8359375,1);
  r1.x = r1.x / r1.y;
  r1.x = log2(r1.x);
  r1.x = 78.84375 * r1.x;
  r0.z = exp2(r1.x);
  }
  if (cb17[2].x != 0) {
    r1.xy = (uint2)v0.xy;
    r1.z = t3[0].val[1840/4];
    r2.xy = (int2)r1.xy & int2(63,63);
    r1.x = (int)r1.z & 31;
    r2.z = cb17[2].y ? r1.x : 31;
    r2.w = 0;
    r1.x = t27.Load(r2.xyzw).x;
    r1.x = r1.x * 2 + -1;
    r1.y = cmp(0 < r1.x);
    r1.z = cmp(r1.x < 0);
    r1.y = (int)-r1.y + (int)r1.z;
    r1.y = (int)r1.y;
    r1.z = 1 + -abs(r1.x);
    r1.z = sqrt(r1.z);
    r1.z = 1 + -r1.z;
    r1.y = r1.y * r1.z;
    r1.x = cb17[2].z ? r1.y : r1.x;
    r0.xyz = r1.xxx * cb17[2].www + r0.xyz;
  }
  o0.xyzw = r0.xyzw;
  return;
}