/*
 * DX12 replacement for shader 0x6F990851 (ps_5_1) -- RDR2 tone-mapping pass.
 *
 * Generated by tools/mech-port.mjs from a 3DMigoto decompilation of the game's
 * own DX12 bytecode (captures/msasm/0x6F990851.ps_5_1.asm), then repaired
 * where the decompiler could not represent an instruction. The arithmetic,
 * register bindings and structured-buffer strides are therefore the game's, not
 * a re-derivation, which is why this file is generated rather than written by
 * hand: retyping the decompilation would only add opportunities for error.
 *
 * Not translated from the Vulkan mod's tonemap_*.frag.vk.glsl. The two renderers
 * differ in this pass; the Vulkan source is used only to decide what RenoDX
 * changes, which is the grading call spliced in at the end.
 *
 * The only behavioural changes are:
 *   - the RenoDX injection constant buffer is added (b13, space50), and
 *   - ApplyGradingAndDisplayMap() runs on the final colour.
 * Everything else, including both tone-map branches and the select between
 * them, is the original arithmetic, so ToneMapper = Vanilla is preserved.
 *
 * Bindings are verified to match the original by tools/verify-bindings.mjs.
 *
 * Unverified in game: this has only been validated by compilation and by
 * comparing the binding slots it reads against the original.
 */
#include "../shared.h"
#include "../tonemap/tonemap.hlsli"

// ---- Created with 3Dmigoto v1.4.9 on Fri Sep 18 01:27:32 2026
struct t118_t {
  float val[59];
};
StructuredBuffer<t118_t> t118 : register(t118);

Buffer<float4> t116 : register(t116);

Texture2D<float4> t114 : register(t114);

Texture2D<float4> t113 : register(t113);

Texture2D<float4> t111 : register(t111);

Texture2D<float4> t109 : register(t109);

Texture2D<float4> t108 : register(t108);

Texture2D<float4> t107 : register(t107);

Texture2D<float4> t106 : register(t106);

Texture2D<float4> t105 : register(t105);

Texture2D<float4> t104 : register(t104);

Texture2D<float4> t103 : register(t103);

Texture2D<float4> t102 : register(t102);

Texture2D<float4> t101 : register(t101);

Texture2D<float4> t100 : register(t100);

Texture2D<float4> t98 : register(t98);

Texture2D<float4> t95 : register(t95);

Texture2D<float4> t94 : register(t94);

Texture2D<float4> t93 : register(t93);

Texture1D<float4> t89 : register(t89);

Texture2D<float4> t90 : register(t90);

Texture2D<float4> t81 : register(t81);

Texture2D<float4> t78 : register(t78);

Texture2D<float4> t77 : register(t77);

Texture2D<float4> t44 : register(t44);

Texture2DArray<float4> t25 : register(t25);

struct t3_t {
  float val[476];
};
StructuredBuffer<t3_t> t3 : register(t3);

struct t2_t {
  float val[501];
};
StructuredBuffer<t2_t> t2 : register(t2);

SamplerState s8_s : register(s8);

SamplerState s2_s : register(s2);

SamplerState s1_s : register(s1);

SamplerState s0_s : register(s0);

cbuffer cb20 : register(b20)
{
  float4 cb20[5];
}

cbuffer cb16 : register(b16)
{
  float4 cb16[88];
}




// 3Dmigoto declarations
#define cmp -


float4 main(
  float4 v0 : SV_Position,
  float4 v1 : TEXCOORD0,
  float v2 : TEXCOORD1) : SV_Target0
{
  float4 o0;
  float4 r0,r1,r2,r3,r4,r5,r6,r7,r8,r9;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.x = t78.SampleLevel(s0_s, v1.xy, 0).x;
  r0.y = 1 + cb16[0].w;
  r0.x = r0.y + -r0.x;
  r0.x = cb16[0].z / r0.x;
  r1.xyz = t90.Sample(s8_s, v1.xy).xyz;
  r0.z = t2[0].val[16/4];
  r1.xyz = r1.xyz * r0.zzz;
  r0.zw = cb16[82].xy * v1.xy;
  r2.xyzw = t114.SampleLevel(s0_s, r0.zw, 0).xyzw;
  r0.z = cmp(r2.z >= 1);
  r0.w = cmp(r2.w < 2);
  r0.z = r0.w ? r0.z : 0;
  if (r0.z != 0) {
    r0.zw = t113.SampleLevel(s0_s, v1.xy, 0).xy;
    r0.zw = cb16[20].xx * r0.zw;
    r0.z = dot(r0.zw, r0.zw);
    r0.z = sqrt(r0.z);
    r0.z = min(cb16[20].z, r0.z);
    r2.xy = r2.xy / r2.zz;
    r0.w = min(2, r2.z);
    r2.xy = r2.xy * r0.ww;
    r1.w = 1 + r0.w;
    r1.w = min(2, r1.w);
    r2.z = (int)r1.w;
    r3.xy = cb16[66].xy * r2.xy;
    r1.w = trunc(r1.w);
    r1.w = -0.5 + r1.w;
    r0.w = r1.w / r0.w;
    r2.xy = cb16[66].xy * -r2.xy;
    r4.x = r0.z * r0.w;
    r5.xyzw = float4(0,0,0,0);
    r0.z = 0;
    while (true) {
      r2.w = cmp((int)r0.z >= (int)r2.z);
      if (r2.w != 0) break;
      r2.w = (int)r0.z;
      r3.zw = float2(0.5,-0.5) + r2.ww;
      r2.w = r3.z / r1.w;
      r6.xy = r3.xy * r2.ww + v1.xy;
      r6.zw = t113.SampleLevel(s0_s, r6.xy, 0).xy;
      r6.zw = cb16[20].xx * r6.zw;
      r3.z = dot(r6.zw, r6.zw);
      r3.z = sqrt(r3.z);
      r3.z = min(cb16[20].z, r3.z);
      r4.w = t77.SampleLevel(s0_s, r6.xy, 0).x;
      r4.w = -r4.w + r0.y;
      r4.w = cb16[0].z / r4.w;
      r6.z = 1 + -r3.z;
      r6.z = saturate(8 * r6.z);
      r6.z = 1 + -r6.z;
      r4.y = r3.z * r0.w;
      r6.w = r4.w + -r0.x;
      r7.xy = saturate(r6.ww * float2(1,-1) + float2(0.5,0.5));
      r3.w = max(0, r3.w);
      r7.zw = saturate(r4.xy + -r3.ww);
      r4.y = dot(r7.xy, r7.zw);
      r4.y = r6.z * r4.y;
      r6.xyz = t94.SampleLevel(s1_s, r6.xy, 0).xyz;
      r7.xy = r2.xy * r2.ww + v1.xy;
      r7.zw = t113.SampleLevel(s0_s, r7.xy, 0).xy;
      r7.zw = cb16[20].xx * r7.zw;
      r2.w = dot(r7.zw, r7.zw);
      r2.w = sqrt(r2.w);
      r2.w = min(cb16[20].z, r2.w);
      r6.w = t77.SampleLevel(s0_s, r7.xy, 0).x;
      r6.w = -r6.w + r0.y;
      r6.w = cb16[0].z / r6.w;
      r7.z = 1 + -r2.w;
      r7.z = saturate(8 * r7.z);
      r7.z = 1 + -r7.z;
      r4.z = r2.w * r0.w;
      r7.w = r6.w + -r0.x;
      r8.xy = saturate(r7.ww * float2(1,-1) + float2(0.5,0.5));
      r8.zw = saturate(r4.xz + -r3.ww);
      r3.w = dot(r8.xy, r8.zw);
      r3.w = r7.z * r3.w;
      r7.xyz = t94.SampleLevel(s1_s, r7.xy, 0).xyz;
      r4.z = cmp(r6.w < r4.w);
      r2.w = cmp(r3.z < r2.w);
      r3.z = r2.w ? r4.z : 0;
      r8.w = r3.z ? r3.w : r4.y;
      r2.w = (int)r2.w | (int)r4.z;
      r2.w = (int)r2.w | (int)r3.z;
      r9.w = r2.w ? r3.w : r4.y;
      r9.xyz = r9.www * r7.xyz;
      r7.xyzw = r9.xyzw + r5.xyzw;
      r8.xyz = r8.www * r6.xyz;
      r5.xyzw = r7.xyzw + r8.xyzw;
      r0.z = (int)r0.z + 1;
    }
    r0.y = (uint)r2.z << 1;
    r0.y = (int)r0.y;
    r2.xyzw = r5.xyzw / r0.yyyy;
  } else {
    r2.xyzw = float4(0,0,0,0);
  }
  r0.y = 1 + -r2.w;
  r0.yzw = r0.yyy * r1.xyz + r2.xyz;
  r1.xyzw = t95.SampleLevel(s1_s, v1.xy, 0).xyzw;
  r1.w = 1 + -r1.w;
  r0.yzw = r1.www * r0.yzw + r1.xyz;
  r1.xyz = t116.Load(float4(0,0,0,0)).xyz;
  r2.xyzw = t116.Load(float4(1,1,1,1)).xyzw;
  r1.w = t44.Load(float4(0,0,0,0)).x;
  r3.xyz = r1.www * r0.yzw;
  r3.x = dot(r3.xyz, float3(0.300000012,0.589999974,0.109999999));
  r3.y = 0.0399999991 + r3.x;
  r3.y = 0.0399999991 / r3.y;
  if (cb16[64].x != 0) {
    r4.xyzw = t109.Sample(s8_s, v1.xy).xyzw;
    r3.z = 9.99999975e-05 + r4.w;
    r3.z = cmp(r3.z >= 1);
    r3.w = 1 + -r4.w;
    r5.xyz = r0.yzw * r3.www + r4.xyz;
    r0.yzw = r3.zzz ? r4.xyz : r5.xyz;
  } else {
    r3.z = 0;
  }
  r0.yzw = r0.yzw * r1.www;
  r0.yzw = min(float3(65504,65504,65504), r0.yzw);
  r3.w = ~(int)r3.z;
  if (r3.z == 0) {
    if (cb16[73].x != 0) {
      r4.xyz = t81.Sample(s2_s, v1.xy).xyz;
      r4.xyz = r4.xyz * r1.www;
      r1.w = dot(r4.xyz, float3(0.300000012,0.589999974,0.109999999));
      r1.w = max(cb16[75].z, r1.w);
      r1.w = min(cb16[75].w, r1.w);
      r4.x = cb16[75].x + r1.w;
      r4.x = log2(r4.x);
      r4.x = cb16[73].y * r4.x;
      r4.x = r4.x * 0.693147182 + cb16[73].z;
      r4.x = -10 + r4.x;
      r1.w = cb16[75].y * r1.w + r4.x;
      r1.w = cb16[68].w + r1.w;
      r1.w = max(cb16[69].x, r1.w);
      r1.w = min(cb16[69].y, r1.w);
      r4.x = cb16[69].z * abs(r1.w);
      r4.y = cmp(0 < r1.w);
      r4.z = cmp(r1.w < 0);
      r4.y = (int)-r4.y + (int)r4.z;
      r4.y = (int)r4.y;
      r1.w = r4.x * r4.y + r1.w;
      r1.w = max(cb16[69].x, r1.w);
      r1.w = min(cb16[69].y, r1.w);
      r4.x = saturate(cb16[73].x);
      r1.w = -v2.x + r1.w;
      r1.w = r4.x * r1.w + v2.x;
      r1.w = exp2(r1.w);
    } else {
      r1.w = v1.z;
    }
    r4.xy = cb16[16].ww * v1.xy;
    r4.xy = r4.xy * float2(1.60000002,0.899999976) + cb16[16].xy;
    r4.xy = frac(r4.xy);
    r4.x = t93.Sample(s2_s, r4.xy).w;
    r4.yzw = float3(0.5,0.5,0.5) * r0.yzw;
    r4.x = -0.5 + r4.x;
    r3.x = r4.x * r3.x;
    r5.xyz = r3.xxx * cb16[16].zzz + r0.yzw;
    r4.xyz = max(r5.xyz, r4.yzw);
    r5.xy = -cb16[53].xy + v1.xy;
    r6.x = dot(cb16[55].xy, r5.xy);
    r6.y = dot(cb16[55].zw, r5.xy);
    r5.xy = cb16[53].zw * r6.xy;
    r3.x = dot(r5.xy, r5.xy);
    r3.x = -cb16[56].x + r3.x;
    r3.x = cb16[56].w * r3.x;
    r3.x = max(0, r3.x);
    r4.w = cmp(r3.x < 1);
    r5.x = -10 * r3.x;
    r5.x = exp2(r5.x);
    r5.x = 1 + -r5.x;
    r5.yz = float2(-1,-2) + r3.xx;
    r3.x = cmp(0 < r5.y);
    r5.y = 10 * r5.z;
    r5.y = exp2(r5.y);
    r3.x = r3.x ? r5.y : 0;
    r3.x = 0.998049974 + r3.x;
    r3.x = r4.w ? r5.x : r3.x;
    r5.xyz = cb16[54].xyz * r4.xyz;
    r5.xyz = r5.xyz * cb16[54].www + -r4.xyz;
    r5.xyz = r3.xxx * r5.xyz + r4.xyz;
    r0.yzw = cb16[54].www ? r5.xyz : r4.xyz;
  } else {
    r1.w = v1.z;
  }
  r3.x = saturate(cb16[60].y * v1.y);
  r3.x = saturate(cb16[57].w + r3.x);
  r4.x = saturate(-cb16[59].w + v1.y);
  r4.x = saturate(cb16[60].x * r4.x);
  r4.x = saturate(-cb16[58].w + r4.x);
  r4.yzw = cb16[59].xyz + -cb16[57].xyz;
  r4.yzw = r3.xxx * r4.yzw + cb16[57].xyz;
  r5.xyz = -cb16[59].xyz + cb16[58].xyz;
  r5.xyz = r4.xxx * r5.xyz + cb16[59].xyz;
  r5.xyz = r5.xyz + -r4.yzw;
  r4.xyz = v1.yyy * r5.xyz + r4.yzw;
  r0.yzw = r4.xyz * r0.yzw;
  if (RENODX_TONE_MAP_TYPE != 0.f) {
    const float renodx_contrast_override = (asuint(cb20[1].x) != 0u) ? cb20[2].z : r1.z;
    r0.yzw = ApplyToneMap(
        r0.xyz,
        cb20[0].w != 0.f,
        r1.w,
        cb20[1].z,
        (uint)cb20[1].x,
        renodx_contrast_override,
        r1.xyz,
        r2.xyzw);
  } else {
  r3.x = cb20[1].x ? cb20[2].z : r1.z;
  r4.x = r1.w / cb20[1].z;
  r4.xyz = r4.xxx * r0.yzw;
  r4.xyz = max(float3(0,0,0), r4.xyz);
  r5.xyz = r1.xxx * r4.xyz + r2.xxx;
  r5.xyz = r4.xyz * r5.xyz + r2.yyy;
  r6.xyz = r1.xxx * r4.xyz + r1.yyy;
  r4.xyz = r4.xyz * r6.xyz + r2.zzz;
  r4.xyz = r5.xyz / r4.xyz;
  r4.xyz = r4.xyz + -r2.www;
  r4.xyz = r4.xyz * r3.xxx;
  r4.xyz = cb20[1].zzz * r4.xyz;
  r0.yzw = r0.yzw * r1.www;
  r0.yzw = max(float3(0,0,0), r0.yzw);
  r5.xyz = r1.xxx * r0.yzw + r2.xxx;
  r5.xyz = r0.yzw * r5.xyz + r2.yyy;
  r1.xyw = r1.xxx * r0.yzw + r1.yyy;
  r0.yzw = r0.yzw * r1.xyw + r2.zzz;
  r0.yzw = r5.xyz / r0.yzw;
  r0.yzw = r0.yzw + -r2.www;
  r0.yzw = saturate(r0.yzw * r1.zzz);
  r0.yzw = cb20[0].www ? r4.xyz : r0.yzw;
  }
  if (r3.z == 0) {
    if (cb16[50].w != 0) {
      r1.xy = -cb16[49].xy + v1.xy;
      r2.x = dot(cb16[51].xy, r1.xy);
      r2.y = dot(cb16[51].zw, r1.xy);
      r1.xy = cb16[49].zw * r2.xy;
      r1.x = dot(r1.xy, r1.xy);
      r1.x = -cb16[52].x + r1.x;
      r1.x = saturate(cb16[52].w * r1.x);
r1.x = t89.Sample(s2_s, r1.xxxx).w;
      r1.x = cb16[50].w * r1.x;
      r1.yzw = cb16[50].xyz + -r0.yzw;
      r0.yzw = r1.xxx * r1.yzw + r0.yzw;
    }
  }
  r1.xyz = cb20[2].www * r0.yzw;
  r2.xyz = log2(r0.yzw);
  r2.xyz = cb20[3].xxx * r2.xyz;
  r2.xyz = exp2(r2.xyz);
  r2.xyz = r2.xyz * cb20[3].yyy + -cb20[3].zzz;
  r4.xyz = cmp(r0.yzw < float3(0.00313080009,0.00313080009,0.00313080009));
  r1.xyz = r4.xyz ? r1.xyz : r2.xyz;
  r1.w = cmp(asint(cb20[0].w) != 0);
  r2.x = cmp(asint(cb20[0].z) == 0);
  r1.w = r1.w ? r2.x : 0;
  r0.yzw = r1.www ? r0.yzw : r1.xyz;
  r1.x = cmp(asint(cb16[19].x) != 0);
  r1.x = r1.x ? r3.w : 0;
  if (r1.x != 0) {
    r2.xyzw = float4(0.0700000003,0.109999999,0.129999995,0.170000002) * cb16[17].xxxx;
    r4.xyzw = v1.xyxy * cb16[17].wwww + r2.xxyy;
    r1.x = dot(r4.xy, float2(12.9898005,78.2330017));
    r1.x = sin(r1.x);
    r1.x = 43758.5469 * r1.x;
    r1.y = dot(r4.zw, float2(12.9898005,78.2330017));
    r1.y = sin(r1.y);
    r1.y = 43758.5469 * r1.y;
    r2.xyzw = v1.xyxy * cb16[17].wwww + r2.zzww;
    r1.z = dot(r2.xy, float2(12.9898005,78.2330017));
    r1.z = sin(r1.z);
    r1.z = 43758.5469 * r1.z;
    r1.xyz = frac(r1.xyz);
    r2.x = dot(r2.zw, float2(12.9898005,78.2330017));
    r2.x = sin(r2.x);
    r2.x = 43758.5469 * r2.x;
    r4.xyzw = float4(0.189999998,0.230000004,0.289999992,0.310000002) * cb16[17].xxxx;
    r5.xyzw = v1.xyxy * cb16[17].wwww + r4.xxyy;
    r2.y = dot(r5.xy, float2(12.9898005,78.2330017));
    r2.y = sin(r2.y);
    r2.y = 43758.5469 * r2.y;
    r2.z = dot(r5.zw, float2(12.9898005,78.2330017));
    r2.z = sin(r2.z);
    r2.z = 43758.5469 * r2.z;
    r4.xyzw = v1.xyxy * cb16[17].wwww + r4.zzww;
    r2.w = dot(r4.xy, float2(12.9898005,78.2330017));
    r2.w = sin(r2.w);
    r2.w = 43758.5469 * r2.w;
    r2.xyzw = frac(r2.xyzw);
    r3.x = dot(r4.zw, float2(12.9898005,78.2330017));
    r3.x = sin(r3.x);
    r3.x = 43758.5469 * r3.x;
    r3.x = frac(r3.x);
    r1.x = r1.x + r1.y;
    r1.x = r1.x + r1.z;
    r1.x = r1.x + r2.x;
    r1.x = r1.x + r2.y;
    r1.x = r1.x + r2.z;
    r1.x = r1.x + r2.w;
    r1.x = r1.x + r3.x;
    r1.x = saturate(r1.x * 0.125 + cb16[17].z);
    r1.y = dot(r0.yzw, float3(0.212599993,0.715200007,0.0722000003));
    r1.z = r1.y * r1.y;
    r1.y = r1.z * r1.y;
    r1.y = r1.x * r1.y;
    r1.y = r1.y * -0.5 + r1.x;
    r1.y = cb16[18].y ? r1.y : r1.x;
    r2.xyz = float3(0.0250000004,0.0250000004,0.0250000004) * r0.yzw;
    r1.z = -0.5 + r1.y;
    r4.xyz = r1.zzz * cb16[18].xxx + r0.yzw;
    r2.xyz = saturate(max(r4.xyz, r2.xyz));
    r1.z = cmp(r1.y < 0.5);
    r2.w = r1.y + r1.y;
    r4.xyz = r2.www * r0.yzw;
    r5.xyz = r0.yzw * r0.yzw;
    r2.w = -r1.y * 2 + 1;
    r5.xyz = r5.xyz * r2.www + r4.xyz;
    r6.xyz = r0.yzw + r0.yzw;
    r2.w = 1 + -r1.y;
    r7.xyz = sqrt(r0.yzw);
    r1.y = r1.y * 2 + -1;
    r7.xyz = r7.xyz * r1.yyy;
    r6.xyz = r6.xyz * r2.www + r7.xyz;
    r5.xyz = r1.zzz ? r5.xyz : r6.xyz;
    r5.xyz = r5.xyz + -r0.yzw;
    r5.xyz = cb16[18].xxx * r5.xyz + r0.yzw;
    r6.xyz = cmp(r0.yzw < float3(0.5,0.5,0.5));
    r1.y = r2.w + r2.w;
    r7.xyz = float3(1,1,1) + -r0.yzw;
    r7.xyz = -r1.yyy * r7.xyz + float3(1,1,1);
    r4.xyz = r6.xyz ? r4.xyz : r7.xyz;
    r4.xyz = r4.xyz + -r0.yzw;
    r4.xyz = cb16[18].xxx * r4.xyz + r0.yzw;
    r2.xyz = cb16[19].www ? r4.xyz : r2.xyz;
    r2.xyz = cb16[19].zzz ? r5.xyz : r2.xyz;
    r0.yzw = cb16[18].www ? r2.xyz : r1.xxx;
  }
  r1.x = dot(float3(0.514900029,0.324400008,0.160699993), r0.yzw);
  r1.y = dot(float3(0.265399992,0.670400023,0.064199999), r0.yzw);
  r1.z = dot(float3(0.0248000007,0.124799997,0.850399971), r0.yzw);
  r1.xyz = max(float3(0.00999999978,0,0), r1.xyz);
  r1.z = r1.y + r1.z;
  r1.x = r1.z / r1.x;
  r1.x = 1 + r1.x;
  r1.x = r1.x * 1.33000004 + -1.67999995;
  r1.x = r1.y * r1.x;
  r1.xyz = cb16[83].xyz * r1.xxx;
  r1.xyz = saturate(cb16[83].www * r1.xyz);
  r2.x = saturate(r3.y * cb16[84].x + cb16[84].y);
  r1.xyz = r1.xyz + -r0.yzw;
  r0.yzw = r2.xxx * r1.xyz + r0.yzw;
  if (cb16[86].w != 0) {
    r1.xy = cb16[87].zy + -cb16[87].wx;
    r1.xy = v1.yx * r1.xy + cb16[87].wx;
    r2.xy = float2(-0.5,-0.5) + v1.xy;
    r2.xy = cb16[86].zz * r2.xy;
    r1.xy = r2.xy / r1.xy;
    r1.xy = -cb16[86].xy + r1.xy;
    r1.xy = float2(0.5,0.5) + r1.xy;
    r1.xyz = t111.Sample(s2_s, r1.xy).xyz;
    r1.xyz = r1.xyz + -r0.yzw;
    r0.yzw = cb16[86].www * r1.xyz + r0.yzw;
  }
  if (r3.z == 0) {
    r1.x = cmp(asint(cb20[1].y) == 0);
    r1.x = r1.x ? r1.w : 0;
    r1.y = max(r0.z, r0.w);
    r1.y = max(r1.y, r0.y);
    r1.y = max(9.99999975e-05, r1.y);
    r1.z = cmp(cb20[1].w < r1.y);
    r1.w = r1.y * cb20[2].x + cb20[2].y;
    r1.z = r1.z ? r1.w : r1.y;
    r1.y = r1.z / r1.y;
    r1.x = r1.x ? 1 : r1.y;
    r2.xyzw = r1.xxxx * r0.wwyz;
    r3.xyw = float3(14.9998999,0.9375,0.05859375) * r2.xwz;
    r1.y = floor(r3.x);
    r1.z = r2.y * 15 + -r1.y;
    r3.x = r1.y * 0.0625 + r3.w;
    r2.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r3.xyxy;
    r3.xyz = t106.Sample(s2_s, r2.xy).xyz;
    r2.xyz = t106.Sample(s2_s, r2.zw).xyz;
    r2.xyz = r2.xyz + -r3.xyz;
    r1.yzw = r1.zzz * r2.xyz + r3.xyz;
    r2.x = t118[0].val[0/4];
    r2.x = cmp(0 < (int)r2.x);
    if (r2.x != 0) {
      r2.xyzw = t98.Sample(s0_s, v1.xy).xyzw;
      r3.x = t118[0].val[4/4];
      r2.xyzw = saturate(r3.xxxx * r2.xyzw);
      r3.xyz = t108.Sample(s2_s, v1.xy).xyz;
      r3.x = dot(r3.xyz, float3(0.212599993,0.715200007,0.0722000003));
      r3.xyzw = r3.xxxx * r2.xyzw;
      r4.xyzw = cmp(r3.xyzw != float4(0,0,0,0));
      if (r4.x != 0) {
        r5.xyw = float3(14.9998999,0.9375,0.05859375) * r1.wzy;
        r4.x = floor(r5.x);
        r5.z = r1.w * 15 + -r4.x;
        r5.x = r4.x * 0.0625 + r5.w;
        r6.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r5.xyxy;
        r5.xyw = t102.Sample(s2_s, r6.xy).xyz;
        r6.xyz = t102.Sample(s2_s, r6.zw).xyz;
        r6.xyz = r6.xyz + -r5.xyw;
        r5.xyz = r5.zzz * r6.xyz + r5.xyw;
        r5.xyz = r5.xyz + -r1.yzw;
        r1.yzw = r3.xxx * r5.xyz + r1.yzw;
      }
      if (r4.y != 0) {
        r5.xyw = float3(14.9998999,0.9375,0.05859375) * r1.wzy;
        r3.x = floor(r5.x);
        r4.x = r1.w * 15 + -r3.x;
        r5.x = r3.x * 0.0625 + r5.w;
        r5.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r5.xyxy;
        r6.xyz = t103.Sample(s2_s, r5.xy).xyz;
        r5.xyz = t103.Sample(s2_s, r5.zw).xyz;
        r5.xyz = r5.xyz + -r6.xyz;
        r5.xyz = r4.xxx * r5.xyz + r6.xyz;
        r5.xyz = r5.xyz + -r1.yzw;
        r1.yzw = r3.yyy * r5.xyz + r1.yzw;
      }
      if (r4.z != 0) {
        r5.xyw = float3(14.9998999,0.9375,0.05859375) * r1.wzy;
        r3.x = floor(r5.x);
        r3.y = r1.w * 15 + -r3.x;
        r5.x = r3.x * 0.0625 + r5.w;
        r5.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r5.xyxy;
        r4.xyz = t104.Sample(s2_s, r5.xy).xyz;
        r5.xyz = t104.Sample(s2_s, r5.zw).xyz;
        r5.xyz = r5.xyz + -r4.xyz;
        r4.xyz = r3.yyy * r5.xyz + r4.xyz;
        r4.xyz = r4.xyz + -r1.yzw;
        r1.yzw = r3.zzz * r4.xyz + r1.yzw;
      }
      if (r4.w != 0) {
        r4.xyw = float3(14.9998999,0.9375,0.05859375) * r1.wzy;
        r3.x = floor(r4.x);
        r3.y = r1.w * 15 + -r3.x;
        r4.x = r3.x * 0.0625 + r4.w;
        r4.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r4.xyxy;
        r5.xyz = t105.Sample(s2_s, r4.xy).xyz;
        r4.xyz = t105.Sample(s2_s, r4.zw).xyz;
        r4.xyz = r4.xyz + -r5.xyz;
        r3.xyz = r3.yyy * r4.xyz + r5.xyz;
        r3.xyz = r3.xyz + -r1.yzw;
        r1.yzw = r3.www * r3.xyz + r1.yzw;
      }
      r2.x = r2.x + r2.y;
      r2.x = r2.x + r2.z;
      r2.x = r2.x + r2.w;
      r2.x = min(1, r2.x);
      r2.x = 1 + -r2.x;
      r3.x = t118[0].val[16/4];
      r3.y = t118[0].val[16/4+1];
      r3.z = t118[0].val[16/4+2];
      r3.w = t118[0].val[16/4+3];
      r4.x = t118[0].val[32/4];
      r4.y = t118[0].val[32/4+1];
      r4.z = t118[0].val[32/4+2];
      r4.w = t118[0].val[32/4+3];
      r2.y = t118[0].val[48/4];
      r2.z = t118[0].val[48/4+1];
      r5.xy = -r3.xz + r0.xx;
      r3.xy = saturate(r5.xy * r3.yw);
      r2.w = 1 + -r3.y;
      r3.y = cmp(r0.x < r3.z);
      r2.w = r3.y ? r3.x : r2.w;
      r2.w = saturate(r2.w + r4.x);
      r3.xyw = float3(14.9998999,0.9375,0.05859375) * r1.wzy;
      r3.z = floor(r3.x);
      r4.x = r1.w * 15 + -r3.z;
      r3.x = r3.z * 0.0625 + r3.w;
      r3.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r3.xyxy;
      r5.xyz = t100.Sample(s2_s, r3.xy).xyz;
      r3.xyz = t100.Sample(s2_s, r3.zw).xyz;
      r3.xyz = r3.xyz + -r5.xyz;
      r3.xyz = r4.xxx * r3.xyz + r5.xyz;
      r3.xyz = r3.xyz + -r1.yzw;
      r3.xyz = r2.www * r3.xyz + r1.yzw;
      r4.xy = -r4.yw + r0.xx;
      r2.w = saturate(r4.x * r4.z);
      r2.y = saturate(r4.y * r2.y);
      r2.y = 1 + -r2.y;
      r0.x = cmp(r0.x < r4.w);
      r0.x = r0.x ? r2.w : r2.y;
      r0.x = saturate(r0.x + r2.z);
      r4.xyw = float3(14.9998999,0.9375,0.05859375) * r3.zyx;
      r2.y = floor(r4.x);
      r2.z = r3.z * 15 + -r2.y;
      r4.x = r2.y * 0.0625 + r4.w;
      r4.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r4.xyxy;
      r5.xyz = t101.Sample(s2_s, r4.xy).xyz;
      r4.xyz = t101.Sample(s2_s, r4.zw).xyz;
      r4.xyz = r4.xyz + -r5.xyz;
      r2.yzw = r2.zzz * r4.xyz + r5.xyz;
      r2.yzw = r2.yzw + -r3.xyz;
      r2.yzw = r2.yzw * r0.xxx;
      r4.xyz = t107.Sample(s2_s, v1.xy).xyz;
      r0.x = dot(r4.xyz, float3(0.212599993,0.715200007,0.0722000003));
      r0.x = r0.x * r2.x;
      r1.yzw = r0.xxx * r2.yzw + r3.xyz;
    }
    r0.yzw = r1.yzw / r1.xxx;
  }
  r1.w = dot(r0.yzw, float3(0.298999995,0.587000012,0.114));
  r0.x = max(r0.z, r0.w);
  r0.x = max(r0.y, r0.x);
  r2.xyz = cb16[41].www ? r0.yzw : r0.xxx;
  r2.xyz = -cb16[42].xyz + r2.xyz;
  r2.xyz = saturate(cb16[41].xyz * r2.xyz);
  r2.xyz = log2(r2.xyz);
  r2.xyz = cb16[42].www * r2.xyz;
  r2.xyz = exp2(r2.xyz);
  r3.xyz = cb16[40].xyz + -cb16[39].xyz;
  r2.xyz = r2.xyz * r3.xyz + cb16[39].xyz;
  r3.xy = (uint2)v0.xy;
  r0.x = t3[0].val[1840/4];
  r3.xy = (int2)r3.xy & int2(63,63);
  r3.z = (int)r0.x & 31;
  r3.w = 0;
  r0.x = t25.Load(r3.xyzw).x;
  r0.x = r0.x * 2 + -1;
  r2.w = cmp(0 < r0.x);
  r3.x = cmp(r0.x < 0);
  r2.w = (int)-r2.w + (int)r3.x;
  r2.w = (int)r2.w;
  r3.x = 1 + -abs(r0.x);
  r3.x = sqrt(r3.x);
  r3.x = 1 + -r3.x;
  r2.w = r3.x * r2.w;
  r0.x = cb20[0].w ? r2.w : r0.x;
  r1.xyz = r0.xxx * r2.xyz + r0.yzw;
  r0.xyzw = saturate(r1.xyzw);
  o0.xyzw = cb20[0].wwww ? r1.xyzw : r0.xyzw;
  o0.xyz = ApplyGradingAndDisplayMap(o0.xyz, v1.xy);
  return o0;
}