/*
 * DX12 replacement for shader 0x737584AF (ps_5_1) -- RDR2 HDR output / PQ encode pass.
 *
 * Generated by tools/output-port.mjs from a 3DMigoto decompilation of the game's
 * own DX12 bytecode (captures/msasm/0x737584AF.ps_5_1.asm), so the resource
 * bindings and everything outside the patched encoder are the game's.
 *
 * RDR2 emits many variants of this pass -- some sample a colour texture, some
 * take the colour from an interpolator, some multiply by a second texture's
 * alpha, one discards below an alpha threshold, one applies a colour-space LUT
 * first. Only the shared tail is patched: the BT.709 -> BT.2020 conversion and
 * the PQ encoder. Each variant's own input stage is left exactly as it was.
 *
 * The only behavioural changes, matching the Vulkan mod's output shaders:
 *   - GammaSafe() runs on the linear colour before the BT.2020 conversion, and
 *   - PQEncodeUI() drives the encoder when a RenoDX tone mapper is active,
 *     instead of the game's own brightness factors.
 * The original encoder arithmetic is kept in the else branch, so ToneMapper =
 * Vanilla is exact.
 *
 * Bindings are verified against the original by tools/verify-bindings.mjs.
 *
 * Unverified in game: validated only by compilation and by comparing the binding
 * slots it reads against the original.
 */
#include "../shared.h"
#include "../output/output.hlsli"

// ---- Created with 3Dmigoto v1.4.9 on Fri Sep 18 01:27:32 2026
Texture3D<float4> t35 : register(t35);

Texture2D<float4> t32 : register(t32);

struct t0_t {
  float val[23];
};
StructuredBuffer<t0_t> t0 : register(t0);

SamplerState s5_s : register(s5);

SamplerState s2_s : register(s2);

cbuffer cb23 : register(b23)
{
  float4 cb23[5];
}

cbuffer cb22 : register(b22)
{
  float4 cb22[11];
}




// 3Dmigoto declarations
#define cmp -


void main(
  float4 v0 : SV_Position0,
  float4 v1 : COLOR0,
  float4 v2 : COLOR1,
  float4 v3 : TEXCOORD0,
  float4 v4 : TEXCOORD1,
  out float4 o0 : SV_Target0)
{
  float4 r0,r1,r2,r3,r4,r5;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xyz = t32.SampleLevel(s5_s, v3.xy, 0).xyz;
  r1.xyz = t32.Gather(s5_s, v3.xy).xyz;
  r2.xyz = t32.Gather(s5_s, v3.xy, int2(0, 0)).xzw;
  r1.w = max(r1.x, r0.y);
  r2.w = min(r1.x, r0.y);
  r1.w = max(r1.z, r1.w);
  r2.w = min(r2.w, r1.z);
  r3.x = max(r2.y, r2.x);
  r3.y = min(r2.y, r2.x);
  r1.w = max(r3.x, r1.w);
  r2.w = min(r3.y, r2.w);
  r3.x = 0.063000001 * r1.w;
  r1.w = -r2.w + r1.w;
  r2.w = max(0, r3.x);
  r2.w = cmp(r1.w >= r2.w);
  if (r2.w != 0) {
    r2.w = t32.SampleLevel(s5_s, v3.xy, 0, int2(0, 0)).y;
    r3.x = t32.SampleLevel(s5_s, v3.xy, 0, int2(0, 0)).y;
    r3.yz = r2.yx + r1.xz;
    r1.w = 1 / r1.w;
    r3.w = r3.y + r3.z;
    r3.yz = r0.yy * float2(-2,-2) + r3.yz;
    r4.x = r2.w + r1.y;
    r2.w = r2.z + r2.w;
    r4.y = r1.z * -2 + r4.x;
    r2.w = r2.y * -2 + r2.w;
    r2.z = r3.x + r2.z;
    r1.y = r3.x + r1.y;
    r3.x = abs(r3.y) * 2 + abs(r4.y);
    r2.w = abs(r3.z) * 2 + abs(r2.w);
    r3.y = r2.x * -2 + r2.z;
    r1.y = r1.x * -2 + r1.y;
    r3.x = abs(r3.y) + r3.x;
    r1.y = abs(r1.y) + r2.w;
    r2.z = r2.z + r4.x;
    r1.y = cmp(r3.x >= r1.y);
    r2.z = r3.w * 2 + r2.z;
    r2.x = r1.y ? r2.y : r2.x;
    r1.x = r1.y ? r1.x : r1.z;
    r1.z = r1.y ? v3.w : v3.z;
    r2.y = r2.z * 0.0833333358 + -r0.y;
    r2.z = r2.x + -r0.y;
    r2.w = r1.x + -r0.y;
    r2.x = r2.x + r0.y;
    r1.x = r1.x + r0.y;
    r3.x = cmp(abs(r2.z) >= abs(r2.w));
    r2.z = max(abs(r2.z), abs(r2.w));
    r1.z = r3.x ? -r1.z : r1.z;
    r1.w = saturate(abs(r2.y) * r1.w);
    r2.y = r1.y ? v3.z : 0;
    r2.w = r1.y ? 0 : v3.w;
    r3.yz = r1.zz * float2(0.5,0.5) + v3.xy;
    r3.y = r1.y ? v3.x : r3.y;
    r3.z = r1.y ? r3.z : v3.y;
    r4.xy = r3.yz + -r2.yw;
    r5.xy = r3.yz + r2.yw;
    r3.y = r1.w * -2 + 3;
    r3.z = t32.SampleLevel(s5_s, r4.xy, 0).y;
    r1.w = r1.w * r1.w;
    r3.w = t32.SampleLevel(s5_s, r5.xy, 0).y;
    r1.x = r3.x ? r2.x : r1.x;
    r2.x = 0.25 * r2.z;
    r2.z = -r1.x * 0.5 + r0.y;
    r1.w = r3.y * r1.w;
    r2.z = cmp(r2.z < 0);
    r3.x = -r1.x * 0.5 + r3.z;
    r3.y = -r1.x * 0.5 + r3.w;
    r3.zw = cmp(abs(r3.xy) >= r2.xx);
    r4.zw = r4.xy + -r2.yw;
    r4.x = r3.z ? r4.x : r4.z;
    r4.z = r3.z ? r4.y : r4.w;
    r4.yw = ~(int2)r3.zw;
    r4.y = (int)r4.w | (int)r4.y;
    r4.w = r5.x + r2.y;
    r5.x = r3.w ? r5.x : r4.w;
    r4.w = r5.y + r2.w;
    r5.z = r3.w ? r5.y : r4.w;
    if (r4.y != 0) {
      if (r3.z == 0) {
        r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
      }
      if (r3.w == 0) {
        r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
      }
      r4.y = -r1.x * 0.5 + r3.x;
      r3.x = r3.z ? r3.x : r4.y;
      r3.z = -r1.x * 0.5 + r3.y;
      r3.y = r3.w ? r3.y : r3.z;
      r3.zw = cmp(abs(r3.xy) >= r2.xx);
      r4.y = r4.x + -r2.y;
      r4.x = r3.z ? r4.x : r4.y;
      r4.y = r4.z + -r2.w;
      r4.z = r3.z ? r4.z : r4.y;
      r4.yw = ~(int2)r3.zw;
      r4.y = (int)r4.w | (int)r4.y;
      r4.w = r5.x + r2.y;
      r5.x = r3.w ? r5.x : r4.w;
      r4.w = r5.z + r2.w;
      r5.z = r3.w ? r5.z : r4.w;
      if (r4.y != 0) {
        if (r3.z == 0) {
          r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
        }
        if (r3.w == 0) {
          r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
        }
        r4.y = -r1.x * 0.5 + r3.x;
        r3.x = r3.z ? r3.x : r4.y;
        r3.z = -r1.x * 0.5 + r3.y;
        r3.y = r3.w ? r3.y : r3.z;
        r3.zw = cmp(abs(r3.xy) >= r2.xx);
        r4.y = r4.x + -r2.y;
        r4.x = r3.z ? r4.x : r4.y;
        r4.y = r4.z + -r2.w;
        r4.z = r3.z ? r4.z : r4.y;
        r4.yw = ~(int2)r3.zw;
        r4.y = (int)r4.w | (int)r4.y;
        r4.w = r5.x + r2.y;
        r5.x = r3.w ? r5.x : r4.w;
        r4.w = r5.z + r2.w;
        r5.z = r3.w ? r5.z : r4.w;
        if (r4.y != 0) {
          if (r3.z == 0) {
            r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
          }
          if (r3.w == 0) {
            r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
          }
          r4.y = -r1.x * 0.5 + r3.x;
          r3.x = r3.z ? r3.x : r4.y;
          r3.z = -r1.x * 0.5 + r3.y;
          r3.y = r3.w ? r3.y : r3.z;
          r3.zw = cmp(abs(r3.xy) >= r2.xx);
          r4.y = r4.x + -r2.y;
          r4.x = r3.z ? r4.x : r4.y;
          r4.y = r4.z + -r2.w;
          r4.z = r3.z ? r4.z : r4.y;
          r4.yw = ~(int2)r3.zw;
          r4.y = (int)r4.w | (int)r4.y;
          r4.w = r5.x + r2.y;
          r5.x = r3.w ? r5.x : r4.w;
          r4.w = r5.z + r2.w;
          r5.z = r3.w ? r5.z : r4.w;
          if (r4.y != 0) {
            if (r3.z == 0) {
              r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
            }
            if (r3.w == 0) {
              r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
            }
            r4.y = -r1.x * 0.5 + r3.x;
            r3.x = r3.z ? r3.x : r4.y;
            r3.z = -r1.x * 0.5 + r3.y;
            r3.y = r3.w ? r3.y : r3.z;
            r3.zw = cmp(abs(r3.xy) >= r2.xx);
            r4.y = -r2.y * 1.5 + r4.x;
            r4.x = r3.z ? r4.x : r4.y;
            r4.y = -r2.w * 1.5 + r4.z;
            r4.z = r3.z ? r4.z : r4.y;
            r4.yw = ~(int2)r3.zw;
            r4.y = (int)r4.w | (int)r4.y;
            r4.w = r2.y * 1.5 + r5.x;
            r5.x = r3.w ? r5.x : r4.w;
            r4.w = r2.w * 1.5 + r5.z;
            r5.z = r3.w ? r5.z : r4.w;
            if (r4.y != 0) {
              if (r3.z == 0) {
                r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
              }
              if (r3.w == 0) {
                r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
              }
              r4.y = -r1.x * 0.5 + r3.x;
              r3.x = r3.z ? r3.x : r4.y;
              r3.z = -r1.x * 0.5 + r3.y;
              r3.y = r3.w ? r3.y : r3.z;
              r3.zw = cmp(abs(r3.xy) >= r2.xx);
              r4.y = -r2.y * 2 + r4.x;
              r4.x = r3.z ? r4.x : r4.y;
              r4.y = -r2.w * 2 + r4.z;
              r4.z = r3.z ? r4.z : r4.y;
              r4.yw = ~(int2)r3.zw;
              r4.y = (int)r4.w | (int)r4.y;
              r4.w = r2.y * 2 + r5.x;
              r5.x = r3.w ? r5.x : r4.w;
              r4.w = r2.w * 2 + r5.z;
              r5.z = r3.w ? r5.z : r4.w;
              if (r4.y != 0) {
                if (r3.z == 0) {
                  r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
                }
                if (r3.w == 0) {
                  r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
                }
                r4.y = -r1.x * 0.5 + r3.x;
                r3.x = r3.z ? r3.x : r4.y;
                r3.z = -r1.x * 0.5 + r3.y;
                r3.y = r3.w ? r3.y : r3.z;
                r3.zw = cmp(abs(r3.xy) >= r2.xx);
                r4.y = -r2.y * 2 + r4.x;
                r4.x = r3.z ? r4.x : r4.y;
                r4.y = -r2.w * 2 + r4.z;
                r4.z = r3.z ? r4.z : r4.y;
                r4.yw = ~(int2)r3.zw;
                r4.y = (int)r4.w | (int)r4.y;
                r4.w = r2.y * 2 + r5.x;
                r5.x = r3.w ? r5.x : r4.w;
                r4.w = r2.w * 2 + r5.z;
                r5.z = r3.w ? r5.z : r4.w;
                if (r4.y != 0) {
                  if (r3.z == 0) {
                    r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
                  }
                  if (r3.w == 0) {
                    r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
                  }
                  r4.y = -r1.x * 0.5 + r3.x;
                  r3.x = r3.z ? r3.x : r4.y;
                  r3.z = -r1.x * 0.5 + r3.y;
                  r3.y = r3.w ? r3.y : r3.z;
                  r3.zw = cmp(abs(r3.xy) >= r2.xx);
                  r4.y = -r2.y * 2 + r4.x;
                  r4.x = r3.z ? r4.x : r4.y;
                  r4.y = -r2.w * 2 + r4.z;
                  r4.z = r3.z ? r4.z : r4.y;
                  r4.yw = ~(int2)r3.zw;
                  r4.y = (int)r4.w | (int)r4.y;
                  r4.w = r2.y * 2 + r5.x;
                  r5.x = r3.w ? r5.x : r4.w;
                  r4.w = r2.w * 2 + r5.z;
                  r5.z = r3.w ? r5.z : r4.w;
                  if (r4.y != 0) {
                    if (r3.z == 0) {
                      r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
                    }
                    if (r3.w == 0) {
                      r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
                    }
                    r4.y = -r1.x * 0.5 + r3.x;
                    r3.x = r3.z ? r3.x : r4.y;
                    r3.z = -r1.x * 0.5 + r3.y;
                    r3.y = r3.w ? r3.y : r3.z;
                    r3.zw = cmp(abs(r3.xy) >= r2.xx);
                    r4.y = -r2.y * 2 + r4.x;
                    r4.x = r3.z ? r4.x : r4.y;
                    r4.y = -r2.w * 2 + r4.z;
                    r4.z = r3.z ? r4.z : r4.y;
                    r4.yw = ~(int2)r3.zw;
                    r4.y = (int)r4.w | (int)r4.y;
                    r4.w = r2.y * 2 + r5.x;
                    r5.x = r3.w ? r5.x : r4.w;
                    r4.w = r2.w * 2 + r5.z;
                    r5.z = r3.w ? r5.z : r4.w;
                    if (r4.y != 0) {
                      if (r3.z == 0) {
                        r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
                      }
                      if (r3.w == 0) {
                        r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
                      }
                      r4.y = -r1.x * 0.5 + r3.x;
                      r3.x = r3.z ? r3.x : r4.y;
                      r3.z = -r1.x * 0.5 + r3.y;
                      r3.y = r3.w ? r3.y : r3.z;
                      r3.zw = cmp(abs(r3.xy) >= r2.xx);
                      r4.y = -r2.y * 4 + r4.x;
                      r4.x = r3.z ? r4.x : r4.y;
                      r4.y = -r2.w * 4 + r4.z;
                      r4.z = r3.z ? r4.z : r4.y;
                      r4.yw = ~(int2)r3.zw;
                      r4.y = (int)r4.w | (int)r4.y;
                      r4.w = r2.y * 4 + r5.x;
                      r5.x = r3.w ? r5.x : r4.w;
                      r4.w = r2.w * 4 + r5.z;
                      r5.z = r3.w ? r5.z : r4.w;
                      if (r4.y != 0) {
                        if (r3.z == 0) {
                          r3.x = t32.SampleLevel(s5_s, r4.xz, 0).y;
                        }
                        if (r3.w == 0) {
                          r3.y = t32.SampleLevel(s5_s, r5.xz, 0).y;
                        }
                        r4.y = -r1.x * 0.5 + r3.x;
                        r3.x = r3.z ? r3.x : r4.y;
                        r1.x = -r1.x * 0.5 + r3.y;
                        r3.y = r3.w ? r3.y : r1.x;
                        r3.zw = cmp(abs(r3.xy) >= r2.xx);
                        r1.x = -r2.y * 8 + r4.x;
                        r4.x = r3.z ? r4.x : r1.x;
                        r1.x = -r2.w * 8 + r4.z;
                        r4.z = r3.z ? r4.z : r1.x;
                        r1.x = r2.y * 8 + r5.x;
                        r5.x = r3.w ? r5.x : r1.x;
                        r1.x = r2.w * 8 + r5.z;
                        r5.z = r3.w ? r5.z : r1.x;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    r1.x = v3.x + -r4.x;
    r2.y = v3.y + -r4.z;
    r1.x = r1.y ? r1.x : r2.y;
    r2.xy = -v3.xy + r5.xz;
    r2.x = r1.y ? r2.x : r2.y;
    r2.yw = cmp(r3.xy < float2(0,0));
    r3.x = r2.x + r1.x;
    r2.yz = cmp((int2)r2.zz != (int2)r2.yw);
    r2.w = 1 / r3.x;
    r3.x = cmp(r1.x < r2.x);
    r1.x = min(r2.x, r1.x);
    r2.x = r3.x ? r2.y : r2.z;
    r1.w = r1.w * r1.w;
    r1.x = r1.x * -r2.w + 0.5;
    r1.x = (int)r1.x & (int)r2.x;
    r1.x = max(r1.x, r1.w);
    r1.xz = r1.xx * r1.zz + v3.xy;
    r2.x = r1.y ? v3.x : r1.x;
    r2.y = r1.y ? r1.z : v3.y;
    r0.xyz = t32.SampleLevel(s5_s, r2.xy, 0).xyz;
  }
  r0.w = t32.Sample(s5_s, v3.xy).w;
  r0.xyzw = r0.xyzw * cb22[8].xyzw + cb22[7].xyzw;
  r0.w = v2.w * r0.w;
  if (cb22[10].x != 0) {
    r0.xyz = t35.SampleLevel(s2_s, r0.xyz, 0).xyz;
  }
  if (cb22[9].y != 0) {
    r0.xyz = GammaSafe(r0.xyz);
    r1.x = dot(float3(0.627403975,0.329281986,0.0433136001), r0.xyz);
    r1.y = dot(float3(0.0690969974,0.919539988,0.0113612004), r0.xyz);
    r1.z = dot(float3(0.0163915996,0.088013202,0.895595014), r0.xyz);
    if (RENODX_TONE_MAP_TYPE != 0.f) {
      r0.xyz = PQEncodeUI(r1.xyz);
    } else {
    r1.xyz = cb23[0].xxx * r1.xyz;
    r1.xyz = r1.xyz / cb23[3].www;
    r1.x = log2(abs(r1.x));
    r1.x = 0.159301758 * r1.x;
    r1.x = exp2(r1.x);
    r1.xw = r1.xx * float2(18.8515625,18.6875) + float2(0.8359375,1);
    r1.x = r1.x / r1.w;
    r1.x = log2(r1.x);
    r1.x = 78.84375 * r1.x;
    r0.x = exp2(r1.x);
    r1.x = log2(abs(r1.y));
    r1.x = 0.159301758 * r1.x;
    r1.x = exp2(r1.x);
    r1.xy = r1.xx * float2(18.8515625,18.6875) + float2(0.8359375,1);
    r1.x = r1.x / r1.y;
    r1.x = log2(r1.x);
    r1.x = 78.84375 * r1.x;
    r0.y = exp2(r1.x);
    r1.x = log2(abs(r1.z));
    r1.x = 0.159301758 * r1.x;
    r1.x = exp2(r1.x);
    r1.xy = r1.xx * float2(18.8515625,18.6875) + float2(0.8359375,1);
    r1.x = r1.x / r1.y;
    r1.x = log2(r1.x);
    r1.x = 78.84375 * r1.x;
    r0.z = exp2(r1.x);
    }
  }
  r1.x = cmp(cb22[9].x == 0.000000);
  r1.yzw = r0.xyz * r0.www;
  r0.xyz = r1.xxx ? r0.xyz : r1.yzw;
  r1.x = t0[0].val[12/4];
  r1.x = r1.x * r0.w;
  r1.y = t0[0].val[12/4];
  r1.y = cmp(r1.y != 1.000000);
  r1.x = r1.x * r1.x;
  o0.z = r1.y ? r1.x : r0.z;
  r0.z = t0[0].val[0/4];
  r0.z = r0.w * r0.z;
  r0.w = cb22[9].z * r0.z;
  r0.w = cb22[9].z ? r0.w : r0.z;
  r1.x = 3.14159274 * r0.w;
  r1.x = cos(r1.x);
  r1.x = -1 + r1.x;
  r1.x = -0.5 * r1.x;
  r0.w = cb22[9].w ? r1.x : r0.w;
  o0.w = saturate(cb22[10].y ? r0.w : r0.z);
  o0.xy = r0.xy;
  return;
}