/*
 * DX12 replacement for shader 0x9CCF855F (ps_5_1) -- RDR2 tone-mapping pass.
 *
 * Generated by tools/mech-port.mjs from a 3DMigoto decompilation of the game's
 * own DX12 bytecode (captures/msasm/0x9CCF855F.ps_5_1.asm), then repaired
 * where the decompiler could not represent an instruction. The arithmetic,
 * register bindings and structured-buffer strides are therefore the game's, not
 * a re-derivation, which is why this file is generated rather than written by
 * hand: retyping the decompilation would only add opportunities for error.
 *
 * Not translated from the Vulkan mod's tonemap_*.frag.vk.glsl. The two renderers
 * differ in this pass; the Vulkan source is used only to decide what RenoDX
 * changes, which is the grading call spliced in at the end.
 *
 * The only behavioural changes are:
 *   - the RenoDX injection constant buffer is added (b13, space50), and
 *   - ApplyGradingAndDisplayMap() runs on the final colour.
 * Everything else, including both tone-map branches and the select between
 * them, is the original arithmetic, so ToneMapper = Vanilla is preserved.
 *
 * Bindings are verified to match the original by tools/verify-bindings.mjs.
 *
 * Unverified in game: this has only been validated by compilation and by
 * comparing the binding slots it reads against the original.
 */
#include "../shared.h"
#include "../tonemap/tonemap.hlsli"

// ---- Created with 3Dmigoto v1.4.9 on Fri Sep 18 01:27:32 2026
struct t118_t {
  float val[59];
};
StructuredBuffer<t118_t> t118 : register(t118);

Buffer<float4> t116 : register(t116);

Texture2D<float4> t111 : register(t111);

Texture2D<float4> t109 : register(t109);

Texture2D<float4> t107 : register(t107);

Texture2D<float4> t106 : register(t106);

Texture2D<float4> t101 : register(t101);

Texture2D<float4> t100 : register(t100);

Texture2D<float4> t93 : register(t93);

Texture1D<float4> t89 : register(t89);

Texture2D<float4> t90 : register(t90);

Texture2D<float4> t81 : register(t81);

Texture2D<float4> t78 : register(t78);

Texture2D<float4> t44 : register(t44);

Texture2DArray<float4> t25 : register(t25);

struct t3_t {
  float val[476];
};
StructuredBuffer<t3_t> t3 : register(t3);

struct t2_t {
  float val[501];
};
StructuredBuffer<t2_t> t2 : register(t2);

SamplerState s8_s : register(s8);

SamplerState s2_s : register(s2);

SamplerState s0_s : register(s0);

cbuffer cb20 : register(b20)
{
  float4 cb20[5];
}

cbuffer cb16 : register(b16)
{
  float4 cb16[88];
}




// 3Dmigoto declarations
#define cmp -


float4 main(
  float4 v0 : SV_Position,
  float4 v1 : TEXCOORD0,
  float v2 : TEXCOORD1) : SV_Target0
{
  float4 o0;
  float4 r0,r1,r2,r3,r4,r5,r6,r7;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xyz = t90.Sample(s8_s, v1.xy).xyz;
  r0.w = t2[0].val[16/4];
  r0.xyz = r0.xyz * r0.www;
  r1.xyz = t116.Load(float4(0,0,0,0)).xyz;
  r2.xyzw = t116.Load(float4(1,1,1,1)).xyzw;
  r0.w = t44.Load(float4(0,0,0,0)).x;
  r3.xyz = r0.xyz * r0.www;
  r1.w = dot(r3.xyz, float3(0.300000012,0.589999974,0.109999999));
  r3.x = 0.0399999991 + r1.w;
  r3.x = 0.0399999991 / r3.x;
  if (cb16[64].x != 0) {
    r4.xyzw = t109.Sample(s8_s, v1.xy).xyzw;
    r3.y = 9.99999975e-05 + r4.w;
    r3.y = cmp(r3.y >= 1);
    r3.z = 1 + -r4.w;
    r5.xyz = r0.xyz * r3.zzz + r4.xyz;
    r0.xyz = r3.yyy ? r4.xyz : r5.xyz;
  } else {
    r3.y = 0;
  }
  r0.xyz = r0.xyz * r0.www;
  r0.xyz = min(float3(65504,65504,65504), r0.xyz);
  r3.z = ~(int)r3.y;
  if (r3.y == 0) {
    if (cb16[73].x != 0) {
      r4.xyz = t81.Sample(s2_s, v1.xy).xyz;
      r4.xyz = r4.xyz * r0.www;
      r0.w = dot(r4.xyz, float3(0.300000012,0.589999974,0.109999999));
      r0.w = max(cb16[75].z, r0.w);
      r0.w = min(cb16[75].w, r0.w);
      r3.w = cb16[75].x + r0.w;
      r3.w = log2(r3.w);
      r3.w = cb16[73].y * r3.w;
      r3.w = r3.w * 0.693147182 + cb16[73].z;
      r3.w = -10 + r3.w;
      r0.w = cb16[75].y * r0.w + r3.w;
      r0.w = cb16[68].w + r0.w;
      r0.w = max(cb16[69].x, r0.w);
      r0.w = min(cb16[69].y, r0.w);
      r3.w = cb16[69].z * abs(r0.w);
      r4.x = cmp(0 < r0.w);
      r4.y = cmp(r0.w < 0);
      r4.x = (int)-r4.x + (int)r4.y;
      r4.x = (int)r4.x;
      r0.w = r3.w * r4.x + r0.w;
      r0.w = max(cb16[69].x, r0.w);
      r0.w = min(cb16[69].y, r0.w);
      r3.w = saturate(cb16[73].x);
      r0.w = -v2.x + r0.w;
      r0.w = r3.w * r0.w + v2.x;
      r0.w = exp2(r0.w);
    } else {
      r0.w = v1.z;
    }
    r4.xy = cb16[16].ww * v1.xy;
    r4.xy = r4.xy * float2(1.60000002,0.899999976) + cb16[16].xy;
    r4.xy = frac(r4.xy);
    r3.w = t93.Sample(s2_s, r4.xy).w;
    r4.xyz = float3(0.5,0.5,0.5) * r0.xyz;
    r3.w = -0.5 + r3.w;
    r1.w = r3.w * r1.w;
    r5.xyz = r1.www * cb16[16].zzz + r0.xyz;
    r4.xyz = max(r5.xyz, r4.xyz);
    r5.xy = -cb16[53].xy + v1.xy;
    r6.x = dot(cb16[55].xy, r5.xy);
    r6.y = dot(cb16[55].zw, r5.xy);
    r5.xy = cb16[53].zw * r6.xy;
    r1.w = dot(r5.xy, r5.xy);
    r1.w = -cb16[56].x + r1.w;
    r1.w = cb16[56].w * r1.w;
    r1.w = max(0, r1.w);
    r3.w = cmp(r1.w < 1);
    r4.w = -10 * r1.w;
    r4.w = exp2(r4.w);
    r4.w = 1 + -r4.w;
    r5.xy = float2(-1,-2) + r1.ww;
    r1.w = cmp(0 < r5.x);
    r5.x = 10 * r5.y;
    r5.x = exp2(r5.x);
    r1.w = r1.w ? r5.x : 0;
    r1.w = 0.998049974 + r1.w;
    r1.w = r3.w ? r4.w : r1.w;
    r5.xyz = cb16[54].xyz * r4.xyz;
    r5.xyz = r5.xyz * cb16[54].www + -r4.xyz;
    r5.xyz = r1.www * r5.xyz + r4.xyz;
    r0.xyz = cb16[54].www ? r5.xyz : r4.xyz;
  } else {
    r0.w = v1.z;
  }
  r1.w = saturate(cb16[60].y * v1.y);
  r1.w = saturate(cb16[57].w + r1.w);
  r3.w = saturate(-cb16[59].w + v1.y);
  r3.w = saturate(cb16[60].x * r3.w);
  r3.w = saturate(-cb16[58].w + r3.w);
  r4.xyz = cb16[59].xyz + -cb16[57].xyz;
  r4.xyz = r1.www * r4.xyz + cb16[57].xyz;
  r5.xyz = -cb16[59].xyz + cb16[58].xyz;
  r5.xyz = r3.www * r5.xyz + cb16[59].xyz;
  r5.xyz = r5.xyz + -r4.xyz;
  r4.xyz = v1.yyy * r5.xyz + r4.xyz;
  r0.xyz = r4.xyz * r0.xyz;
  if (RENODX_TONE_MAP_TYPE != 0.f) {
    const float renodx_contrast_override = (asuint(cb20[1].x) != 0u) ? cb20[2].z : r1.z;
    r0.xyz = ApplyToneMap(
        r0.xyz,
        cb20[0].w != 0.f,
        r0.w,
        cb20[1].z,
        (uint)cb20[1].x,
        renodx_contrast_override,
        r1.xyz,
        r2.xyzw);
  } else {
  r1.w = cb20[1].x ? cb20[2].z : r1.z;
  r3.w = r0.w / cb20[1].z;
  r4.xyz = r3.www * r0.xyz;
  r4.xyz = max(float3(0,0,0), r4.xyz);
  r5.xyz = r1.xxx * r4.xyz + r2.xxx;
  r5.xyz = r4.xyz * r5.xyz + r2.yyy;
  r6.xyz = r1.xxx * r4.xyz + r1.yyy;
  r4.xyz = r4.xyz * r6.xyz + r2.zzz;
  r4.xyz = r5.xyz / r4.xyz;
  r4.xyz = r4.xyz + -r2.www;
  r4.xyz = r4.xyz * r1.www;
  r4.xyz = cb20[1].zzz * r4.xyz;
  r0.xyz = r0.xyz * r0.www;
  r0.xyz = max(float3(0,0,0), r0.xyz);
  r5.xyz = r1.xxx * r0.xyz + r2.xxx;
  r5.xyz = r0.xyz * r5.xyz + r2.yyy;
  r1.xyw = r1.xxx * r0.xyz + r1.yyy;
  r0.xyz = r0.xyz * r1.xyw + r2.zzz;
  r0.xyz = r5.xyz / r0.xyz;
  r0.xyz = r0.xyz + -r2.www;
  r0.xyz = saturate(r0.xyz * r1.zzz);
  r0.xyz = cb20[0].www ? r4.xyz : r0.xyz;
  }
  if (r3.y == 0) {
    if (cb16[50].w != 0) {
      r1.xy = -cb16[49].xy + v1.xy;
      r2.x = dot(cb16[51].xy, r1.xy);
      r2.y = dot(cb16[51].zw, r1.xy);
      r1.xy = cb16[49].zw * r2.xy;
      r0.w = dot(r1.xy, r1.xy);
      r0.w = -cb16[52].x + r0.w;
      r0.w = saturate(cb16[52].w * r0.w);
r0.w = t89.Sample(s2_s, r0.wwww).w;
      r0.w = cb16[50].w * r0.w;
      r1.xyz = cb16[50].xyz + -r0.xyz;
      r0.xyz = r0.www * r1.xyz + r0.xyz;
    }
  }
  r1.xyz = cb20[2].www * r0.xyz;
  r2.xyz = log2(r0.xyz);
  r2.xyz = cb20[3].xxx * r2.xyz;
  r2.xyz = exp2(r2.xyz);
  r2.xyz = r2.xyz * cb20[3].yyy + -cb20[3].zzz;
  r4.xyz = cmp(r0.xyz < float3(0.00313080009,0.00313080009,0.00313080009));
  r1.xyz = r4.xyz ? r1.xyz : r2.xyz;
  r0.w = cmp(asint(cb20[0].w) != 0);
  r1.w = cmp(asint(cb20[0].z) == 0);
  r0.w = r0.w ? r1.w : 0;
  r0.xyz = r0.www ? r0.xyz : r1.xyz;
  r1.x = cmp(asint(cb16[19].x) != 0);
  r1.x = r1.x ? r3.z : 0;
  if (r1.x != 0) {
    r1.xyzw = float4(0.0700000003,0.109999999,0.129999995,0.170000002) * cb16[17].xxxx;
    r2.xyzw = v1.xyxy * cb16[17].wwww + r1.xxyy;
    r1.x = dot(r2.xy, float2(12.9898005,78.2330017));
    r1.x = sin(r1.x);
    r1.x = 43758.5469 * r1.x;
    r1.y = dot(r2.zw, float2(12.9898005,78.2330017));
    r1.y = sin(r1.y);
    r1.y = 43758.5469 * r1.y;
    r2.xyzw = v1.xyxy * cb16[17].wwww + r1.zzww;
    r1.z = dot(r2.xy, float2(12.9898005,78.2330017));
    r1.z = sin(r1.z);
    r1.z = 43758.5469 * r1.z;
    r1.w = dot(r2.zw, float2(12.9898005,78.2330017));
    r1.w = sin(r1.w);
    r1.w = 43758.5469 * r1.w;
    r1.xyzw = frac(r1.xyzw);
    r2.xyzw = float4(0.189999998,0.230000004,0.289999992,0.310000002) * cb16[17].xxxx;
    r4.xyzw = v1.xyxy * cb16[17].wwww + r2.xxyy;
    r2.x = dot(r4.xy, float2(12.9898005,78.2330017));
    r2.x = sin(r2.x);
    r2.x = 43758.5469 * r2.x;
    r2.y = dot(r4.zw, float2(12.9898005,78.2330017));
    r2.y = sin(r2.y);
    r2.y = 43758.5469 * r2.y;
    r4.xyzw = v1.xyxy * cb16[17].wwww + r2.zzww;
    r2.z = dot(r4.xy, float2(12.9898005,78.2330017));
    r2.z = sin(r2.z);
    r2.z = 43758.5469 * r2.z;
    r2.w = dot(r4.zw, float2(12.9898005,78.2330017));
    r2.w = sin(r2.w);
    r2.w = 43758.5469 * r2.w;
    r2.xyzw = frac(r2.xyzw);
    r1.x = r1.x + r1.y;
    r1.x = r1.x + r1.z;
    r1.x = r1.x + r1.w;
    r1.x = r1.x + r2.x;
    r1.x = r1.x + r2.y;
    r1.x = r1.x + r2.z;
    r1.x = r1.x + r2.w;
    r1.x = saturate(r1.x * 0.125 + cb16[17].z);
    r1.y = dot(r0.xyz, float3(0.212599993,0.715200007,0.0722000003));
    r1.z = r1.y * r1.y;
    r1.y = r1.z * r1.y;
    r1.y = r1.x * r1.y;
    r1.y = r1.y * -0.5 + r1.x;
    r1.y = cb16[18].y ? r1.y : r1.x;
    r2.xyz = float3(0.0250000004,0.0250000004,0.0250000004) * r0.xyz;
    r1.z = -0.5 + r1.y;
    r4.xyz = r1.zzz * cb16[18].xxx + r0.xyz;
    r2.xyz = saturate(max(r4.xyz, r2.xyz));
    r1.z = cmp(r1.y < 0.5);
    r1.w = r1.y + r1.y;
    r4.xyz = r1.www * r0.xyz;
    r5.xyz = r0.xyz * r0.xyz;
    r1.w = -r1.y * 2 + 1;
    r5.xyz = r5.xyz * r1.www + r4.xyz;
    r6.xyz = r0.xyz + r0.xyz;
    r1.w = 1 + -r1.y;
    r7.xyz = sqrt(r0.xyz);
    r1.y = r1.y * 2 + -1;
    r7.xyz = r7.xyz * r1.yyy;
    r6.xyz = r6.xyz * r1.www + r7.xyz;
    r5.xyz = r1.zzz ? r5.xyz : r6.xyz;
    r5.xyz = r5.xyz + -r0.xyz;
    r5.xyz = cb16[18].xxx * r5.xyz + r0.xyz;
    r6.xyz = cmp(r0.xyz < float3(0.5,0.5,0.5));
    r1.y = r1.w + r1.w;
    r7.xyz = float3(1,1,1) + -r0.xyz;
    r1.yzw = -r1.yyy * r7.xyz + float3(1,1,1);
    r1.yzw = r6.xyz ? r4.xyz : r1.yzw;
    r1.yzw = r1.yzw + -r0.xyz;
    r1.yzw = cb16[18].xxx * r1.yzw + r0.xyz;
    r1.yzw = cb16[19].www ? r1.yzw : r2.xyz;
    r1.yzw = cb16[19].zzz ? r5.xyz : r1.yzw;
    r0.xyz = cb16[18].www ? r1.yzw : r1.xxx;
  }
  r1.x = dot(float3(0.514900029,0.324400008,0.160699993), r0.xyz);
  r1.y = dot(float3(0.265399992,0.670400023,0.064199999), r0.xyz);
  r1.z = dot(float3(0.0248000007,0.124799997,0.850399971), r0.xyz);
  r1.xyz = max(float3(0.00999999978,0,0), r1.xyz);
  r1.z = r1.y + r1.z;
  r1.x = r1.z / r1.x;
  r1.x = 1 + r1.x;
  r1.x = r1.x * 1.33000004 + -1.67999995;
  r1.x = r1.y * r1.x;
  r1.xyz = cb16[83].xyz * r1.xxx;
  r1.xyz = saturate(cb16[83].www * r1.xyz);
  r1.w = saturate(r3.x * cb16[84].x + cb16[84].y);
  r1.xyz = r1.xyz + -r0.xyz;
  r0.xyz = r1.www * r1.xyz + r0.xyz;
  if (cb16[86].w != 0) {
    r1.xy = cb16[87].zy + -cb16[87].wx;
    r1.xy = v1.yx * r1.xy + cb16[87].wx;
    r1.zw = float2(-0.5,-0.5) + v1.xy;
    r1.zw = cb16[86].zz * r1.zw;
    r1.xy = r1.zw / r1.xy;
    r1.xy = -cb16[86].xy + r1.xy;
    r1.xy = float2(0.5,0.5) + r1.xy;
    r1.xyz = t111.Sample(s2_s, r1.xy).xyz;
    r1.xyz = r1.xyz + -r0.xyz;
    r0.xyz = cb16[86].www * r1.xyz + r0.xyz;
  }
  if (r3.y == 0) {
    r1.x = cmp(asint(cb20[1].y) == 0);
    r0.w = r0.w ? r1.x : 0;
    r1.x = max(r0.y, r0.z);
    r1.x = max(r1.x, r0.x);
    r1.x = max(9.99999975e-05, r1.x);
    r1.y = cmp(cb20[1].w < r1.x);
    r1.z = r1.x * cb20[2].x + cb20[2].y;
    r1.y = r1.y ? r1.z : r1.x;
    r1.x = r1.y / r1.x;
    r0.w = r0.w ? 1 : r1.x;
    r1.xyzw = r0.zzxy * r0.wwww;
    r2.xyw = float3(14.9998999,0.9375,0.05859375) * r1.xwz;
    r1.x = floor(r2.x);
    r1.y = r1.y * 15 + -r1.x;
    r2.x = r1.x * 0.0625 + r2.w;
    r2.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r2.xyxy;
    r1.xzw = t106.Sample(s2_s, r2.xy).xyz;
    r2.xyz = t106.Sample(s2_s, r2.zw).xyz;
    r2.xyz = r2.xyz + -r1.xzw;
    r1.xyz = r1.yyy * r2.xyz + r1.xzw;
    r1.w = t118[0].val[0/4];
    r1.w = cmp(0 < (int)r1.w);
    if (r1.w != 0) {
      r1.w = t78.SampleLevel(s0_s, v1.xy, 0).x;
      r2.x = 1 + cb16[0].w;
      r1.w = r2.x + -r1.w;
      r1.w = cb16[0].z / r1.w;
      r2.x = t118[0].val[16/4];
      r2.y = t118[0].val[16/4+1];
      r2.z = t118[0].val[16/4+2];
      r2.w = t118[0].val[16/4+3];
      r3.x = t118[0].val[32/4];
      r3.y = t118[0].val[32/4+1];
      r3.z = t118[0].val[32/4+2];
      r3.w = t118[0].val[32/4+3];
      r4.x = t118[0].val[48/4];
      r4.y = t118[0].val[48/4+1];
      r4.zw = -r2.xz + r1.ww;
      r2.xy = saturate(r4.zw * r2.yw);
      r2.y = 1 + -r2.y;
      r2.z = cmp(r1.w < r2.z);
      r2.x = r2.z ? r2.x : r2.y;
      r2.x = saturate(r2.x + r3.x);
      r5.xyw = float3(14.9998999,0.9375,0.05859375) * r1.zyx;
      r2.y = floor(r5.x);
      r2.z = r1.z * 15 + -r2.y;
      r5.x = r2.y * 0.0625 + r5.w;
      r5.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r5.xyxy;
      r6.xyz = t100.Sample(s2_s, r5.xy).xyz;
      r5.xyz = t100.Sample(s2_s, r5.zw).xyz;
      r5.xyz = r5.xyz + -r6.xyz;
      r2.yzw = r2.zzz * r5.xyz + r6.xyz;
      r2.yzw = r2.yzw + -r1.xyz;
      r2.xyz = r2.xxx * r2.yzw + r1.xyz;
      r3.xy = -r3.yw + r1.ww;
      r2.w = saturate(r3.x * r3.z);
      r3.x = saturate(r3.y * r4.x);
      r3.x = 1 + -r3.x;
      r1.w = cmp(r1.w < r3.w);
      r1.w = r1.w ? r2.w : r3.x;
      r1.w = saturate(r1.w + r4.y);
      r3.xyw = float3(14.9998999,0.9375,0.05859375) * r2.zyx;
      r2.w = floor(r3.x);
      r3.z = r2.z * 15 + -r2.w;
      r3.x = r2.w * 0.0625 + r3.w;
      r4.xyzw = float4(0.001953125,0.03125,0.064453125,0.03125) + r3.xyxy;
      r3.xyw = t101.Sample(s2_s, r4.xy).xyz;
      r4.xyz = t101.Sample(s2_s, r4.zw).xyz;
      r4.xyz = r4.xyz + -r3.xyw;
      r3.xyz = r3.zzz * r4.xyz + r3.xyw;
      r3.xyz = r3.xyz + -r2.xyz;
      r3.xyz = r3.xyz * r1.www;
      r4.xyz = t107.Sample(s2_s, v1.xy).xyz;
      r1.w = dot(r4.xyz, float3(0.212599993,0.715200007,0.0722000003));
      r1.xyz = r1.www * r3.xyz + r2.xyz;
    }
    r0.xyz = r1.xyz / r0.www;
  }
  r1.w = dot(r0.xyz, float3(0.298999995,0.587000012,0.114));
  r0.w = max(r0.y, r0.z);
  r0.w = max(r0.x, r0.w);
  r2.xyz = cb16[41].www ? r0.xyz : r0.www;
  r2.xyz = -cb16[42].xyz + r2.xyz;
  r2.xyz = saturate(cb16[41].xyz * r2.xyz);
  r2.xyz = log2(r2.xyz);
  r2.xyz = cb16[42].www * r2.xyz;
  r2.xyz = exp2(r2.xyz);
  r3.xyz = cb16[40].xyz + -cb16[39].xyz;
  r2.xyz = r2.xyz * r3.xyz + cb16[39].xyz;
  r3.xy = (uint2)v0.xy;
  r0.w = t3[0].val[1840/4];
  r3.xy = (int2)r3.xy & int2(63,63);
  r3.z = (int)r0.w & 31;
  r3.w = 0;
  r0.w = t25.Load(r3.xyzw).x;
  r0.w = r0.w * 2 + -1;
  r2.w = cmp(0 < r0.w);
  r3.x = cmp(r0.w < 0);
  r2.w = (int)-r2.w + (int)r3.x;
  r2.w = (int)r2.w;
  r3.x = 1 + -abs(r0.w);
  r3.x = sqrt(r3.x);
  r3.x = 1 + -r3.x;
  r2.w = r3.x * r2.w;
  r0.w = cb20[0].w ? r2.w : r0.w;
  r1.xyz = r0.www * r2.xyz + r0.xyz;
  r0.xyzw = saturate(r1.xyzw);
  o0.xyzw = cb20[0].wwww ? r1.xyzw : r0.xyzw;
  o0.xyz = ApplyGradingAndDisplayMap(o0.xyz, v1.xy);
  return o0;
}