/*
 * DX12 replacement for shader 0x9DF4FCED (ps_5_1) -- RDR2 HDR output / PQ encode pass.
 *
 * Generated by tools/output-port.mjs from a 3DMigoto decompilation of the game's
 * own DX12 bytecode (captures/msasm/0x9DF4FCED.ps_5_1.asm), so the resource
 * bindings and everything outside the patched encoder are the game's.
 *
 * RDR2 emits many variants of this pass -- some sample a colour texture, some
 * take the colour from an interpolator, some multiply by a second texture's
 * alpha, one discards below an alpha threshold, one applies a colour-space LUT
 * first. Only the shared tail is patched: the BT.709 -> BT.2020 conversion and
 * the PQ encoder. Each variant's own input stage is left exactly as it was.
 *
 * The only behavioural changes, matching the Vulkan mod's output shaders:
 *   - GammaSafe() runs on the linear colour before the BT.2020 conversion, and
 *   - PQEncodeUI() drives the encoder when a RenoDX tone mapper is active,
 *     instead of the game's own brightness factors.
 * The original encoder arithmetic is kept in the else branch, so ToneMapper =
 * Vanilla is exact.
 *
 * Bindings are verified against the original by tools/verify-bindings.mjs.
 *
 * Unverified in game: validated only by compilation and by comparing the binding
 * slots it reads against the original.
 */
#include "../shared.h"
#include "../output/output.hlsli"

// ---- Created with 3Dmigoto v1.4.9 on Fri Sep 18 01:27:32 2026
Texture3D<float4> t35 : register(t35);

Texture2D<float4> t32 : register(t32);

struct t0_t {
  float val[23];
};
StructuredBuffer<t0_t> t0 : register(t0);

SamplerState s5_s : register(s5);

SamplerState s2_s : register(s2);

cbuffer cb23 : register(b23)
{
  float4 cb23[5];
}

cbuffer cb22 : register(b22)
{
  float4 cb22[11];
}




// 3Dmigoto declarations
#define cmp -


void main(
  float4 v0 : SV_Position0,
  float4 v1 : COLOR0,
  float4 v2 : COLOR1,
  float2 v3 : TEXCOORD0,
  out float4 o0 : SV_Target0)
{
  float4 r0,r1;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.x = t32.Sample(s5_s, v3.xy).x;
  r0.xyzw = r0.xxxx * cb22[8].xyzw + cb22[7].xyzw;
  r0.w = v2.w * r0.w;
  if (cb22[10].x != 0) {
    r0.xyz = t35.SampleLevel(s2_s, r0.xyz, 0).xyz;
  }
  if (cb22[9].y != 0) {
    r0.xyz = GammaSafe(r0.xyz);
    r1.x = dot(float3(0.627403975,0.329281986,0.0433136001), r0.xyz);
    r1.y = dot(float3(0.0690969974,0.919539988,0.0113612004), r0.xyz);
    r1.z = dot(float3(0.0163915996,0.088013202,0.895595014), r0.xyz);
    if (RENODX_TONE_MAP_TYPE != 0.f) {
      r0.xyz = PQEncodeUI(r1.xyz);
    } else {
    r1.xyz = cb23[0].xxx * r1.xyz;
    r1.xyz = r1.xyz / cb23[3].www;
    r1.x = log2(abs(r1.x));
    r1.x = 0.159301758 * r1.x;
    r1.x = exp2(r1.x);
    r1.xw = r1.xx * float2(18.8515625,18.6875) + float2(0.8359375,1);
    r1.x = r1.x / r1.w;
    r1.x = log2(r1.x);
    r1.x = 78.84375 * r1.x;
    r0.x = exp2(r1.x);
    r1.x = log2(abs(r1.y));
    r1.x = 0.159301758 * r1.x;
    r1.x = exp2(r1.x);
    r1.xy = r1.xx * float2(18.8515625,18.6875) + float2(0.8359375,1);
    r1.x = r1.x / r1.y;
    r1.x = log2(r1.x);
    r1.x = 78.84375 * r1.x;
    r0.y = exp2(r1.x);
    r1.x = log2(abs(r1.z));
    r1.x = 0.159301758 * r1.x;
    r1.x = exp2(r1.x);
    r1.xy = r1.xx * float2(18.8515625,18.6875) + float2(0.8359375,1);
    r1.x = r1.x / r1.y;
    r1.x = log2(r1.x);
    r1.x = 78.84375 * r1.x;
    r0.z = exp2(r1.x);
    }
  }
  r1.x = cmp(cb22[9].x == 0.000000);
  r1.yzw = r0.xyz * r0.www;
  r0.xyz = r1.xxx ? r0.xyz : r1.yzw;
  r1.x = t0[0].val[12/4];
  r1.x = r1.x * r0.w;
  r1.y = t0[0].val[12/4];
  r1.y = cmp(r1.y != 1.000000);
  r1.x = r1.x * r1.x;
  o0.z = r1.y ? r1.x : r0.z;
  r0.z = t0[0].val[0/4];
  r0.z = r0.w * r0.z;
  r0.w = cb22[9].z * r0.z;
  r0.w = cb22[9].z ? r0.w : r0.z;
  r1.x = 3.14159274 * r0.w;
  r1.x = cos(r1.x);
  r1.x = -1 + r1.x;
  r1.x = -0.5 * r1.x;
  r0.w = cb22[9].w ? r1.x : r0.w;
  o0.w = saturate(cb22[10].y ? r0.w : r0.z);
  o0.xy = r0.xy;
  return;
}